/**
 * The behaviour layer (complexity-layer #2): a block's input→output truth table GENERATED by running
 * its real circuit through the logic engine. Proves the generated table is correct for a primitive gate
 * AND for a real multi-gate composite (the half-adder, which expands to XOR + AND), and that a block
 * with no enumerable inputs/outputs returns null.
 */

import { describe, expect, test } from 'vitest'
import { HALF_ADDER_BLOCK, NAND2_BLOCK, XOR_BLOCK } from '../src/renderer/builtin-blocks.ts'
import { characterizeBlock, type TruthTable } from '../src/renderer/logic-sim.ts'

/** Render a table as { 'ab' : 'outbits' } keyed by the input bits (inputs[0] is the first char). */
const rowMap = (t: TruthTable): Record<string, string> =>
  Object.fromEntries(
    t.rows.map((r) => [
      r.in.map((b) => (b ? '1' : '0')).join(''),
      r.out.map((b) => (b ? '1' : '0')).join(''),
    ]),
  )

describe('characterizeBlock — behaviour generated from the real circuit', () => {
  test('NAND → its truth table', () => {
    const t = characterizeBlock(NAND2_BLOCK)
    expect(t).not.toBeNull()
    const table = t as TruthTable
    expect(table.inputs).toEqual(['a', 'b'])
    expect(table.outputs).toEqual(['out'])
    expect(rowMap(table)).toEqual({ '00': '1', '10': '1', '01': '1', '11': '0' })
  })

  test('XOR → its truth table', () => {
    const t = characterizeBlock(XOR_BLOCK)
    expect(rowMap(t as TruthTable)).toEqual({ '00': '0', '10': '1', '01': '1', '11': '0' })
  })

  test('half-adder (a REAL multi-gate composite) → sum + carry', () => {
    const t = characterizeBlock(HALF_ADDER_BLOCK)
    expect(t).not.toBeNull()
    const table = t as TruthTable
    expect(table.inputs).toEqual(['a', 'b'])
    expect(table.outputs).toEqual(['sum', 'carry'])
    // sum = a XOR b, carry = a AND b; out bits are [sum, carry]
    expect(rowMap(table)).toEqual({ '00': '00', '10': '10', '01': '10', '11': '01' })
  })
})
