# This file is generated by scripts/codegen-backend.py from blocks.yaml. Do not edit by hand. See ADR-003.
"""Generated parameter mapping.

Authored by scripts/codegen-backend.py from blocks.yaml. Do not edit
by hand; re-run `npm run codegen` after editing the manifest.

synth.py's `_build_params` is a thin wrapper around `build_params`
defined here (post-Sprint 21 Phase 1 cutover; see ADR-003).
"""

SAMPLE_RATE = 44100


def build_params(node_type: str, data: dict) -> dict:
    params: dict = {}
    if node_type in ("oscillator", "triangle", "sawtooth", "sine"):
        if "freq" in data:
            params["freq_hz"] = int(data["freq"])
        params["sample_rate"] = SAMPLE_RATE
    elif node_type == "wavetable":
        if "freq" in data:
            params["freq_hz"] = int(data["freq"])
        if "shape" in data:
            params["shape"] = str(data["shape"])
        params["sample_rate"] = SAMPLE_RATE
    elif node_type in ("constant", "byteconstant"):
        if "value" in data:
            params["value"] = int(data["value"])
    elif node_type == "adsr":
        if "attack_ms" in data:
            params["attack_ms"] = int(data["attack_ms"])
        if "decay_ms" in data:
            params["decay_ms"] = int(data["decay_ms"])
        if "sustain_level" in data:
            params["sustain_level"] = int(data["sustain_level"])
        if "release_ms" in data:
            params["release_ms"] = int(data["release_ms"])
        params["sample_rate"] = SAMPLE_RATE
    elif node_type == "gate":
        if "rate_hz" in data:
            params["rate_hz"] = int(data["rate_hz"])
        if "duty_pct" in data:
            params["duty_pct"] = int(data["duty_pct"])
        params["sample_rate"] = SAMPLE_RATE
    elif node_type in ("lowpass", "highpass"):
        if "cutoff_hz" in data:
            params["cutoff_hz"] = int(data["cutoff_hz"])
        params["sample_rate"] = SAMPLE_RATE
    elif node_type == "bandpass":
        if "center_hz" in data:
            params["center_hz"] = int(data["center_hz"])
        params["sample_rate"] = SAMPLE_RATE
    elif node_type == "fm":
        if "carrier_freq" in data:
            params["carrier_freq"] = int(data["carrier_freq"])
        if "modulator_freq" in data:
            params["modulator_freq"] = int(data["modulator_freq"])
        if "mod_depth" in data:
            params["mod_depth"] = int(data["mod_depth"])
        params["sample_rate"] = SAMPLE_RATE
    elif node_type == "bitcrusher":
        if "bits" in data:
            params["bits"] = int(data["bits"])
    elif node_type == "delay":
        if "delay_samples" in data:
            params["delay_samples"] = int(data["delay_samples"])
    elif node_type == "distortion":
        if "threshold" in data:
            params["threshold"] = int(data["threshold"])
    elif node_type == "counter":
        if "max_value" in data:
            params["max_value"] = int(data["max_value"])
    elif node_type == "pixelrange":
        if "start" in data:
            params["start"] = int(data["start"])
        if "end" in data:
            params["end"] = int(data["end"])
    elif node_type == "solidcolor":
        if "color" in data:
            params["color"] = str(data["color"])
    elif node_type == "shifter":
        if "direction" in data:
            params["direction"] = str(data["direction"])
        if "amount" in data:
            params["amount"] = int(data["amount"])
    elif node_type == "rom":
        contents = data.get("contents", [])
        if isinstance(contents, list):
            params["contents"] = [int(v) for v in contents[:16]]
        else:
            params["contents"] = []
    return params
