"""ChipBlocks fab platform registry — Python side.

Per ADR-005, this package holds the fab-target metadata loaded from the
four active manifests at repo root (shuttles.yaml + pdks.yaml +
packages.yaml + flows.yaml). The actual data lives in the generated
module ._registry_gen, regenerated by `scripts/codegen-shuttles-
backend.py` on any manifest edit.

S25-2: this package is shadow data — build.py + tinytapeout.py still
use their hardcoded constants. S25-3 swaps the production code to
consume from here.

Future per-shuttle adapter modules will land in this package as new
shuttle tiers are added (e.g. backend/shuttles/cb_mini.py once that
tier ships). Today the adapter for FPGA boards lives in build.py and
the adapter for tt-pico lives in tinytapeout.py; both stay referenced
by the manifest's `adapter_path` field.
"""

from ._registry_gen import (
    SHUTTLES,
    ALIASES,
    PDKS,
    PACKAGES,
    FLOWS,
    resolve_shuttle,
)

__all__ = [
    'SHUTTLES',
    'ALIASES',
    'PDKS',
    'PACKAGES',
    'FLOWS',
    'resolve_shuttle',
]
