# This file is generated by scripts/codegen-shuttles-backend.py from
# shuttles.yaml + pdks.yaml + packages.yaml + flows.yaml. Do not edit
# by hand. See ADR-005 (../../ADR-005-modular-fab-platform.md).
"""Generated fab-platform registry.

Four manifest registries (SHUTTLES, PDKS, PACKAGES, FLOWS) loaded from
the corresponding YAML files at repo root and validated against their
JSON Schemas at codegen time, plus an ALIASES map for legacy --target
argument names. Per ADR-005, this module is the single Python-side
source of truth for fab metadata.

S25-2 status: this module is shadow data — build.py + tinytapeout.py
still use their hardcoded constants. The matching test in
backend/tests/test_fab_manifests.py asserts that this generated module
agrees with those constants field-for-field. S25-3 swaps the
production code to consume from this module.
"""

# Shuttle registry: id -> dict of fields straight from shuttles.yaml.
SHUTTLES = {
    'icestick': {
        'id': 'icestick',
        'label': 'Lattice iCEstick',
        'kind': 'fpga-board',
        'chip_family': 'hx1k',
        'fpga_package': 'tq144',
        'clock_hz': 12000000,
        'clock_pin': '21',
        'audio_pin': '112',
        'flow': 'yosys-nextpnr-ice40',
        'free_for_open_source': True,
        'estimated_cost_usd': 30,
        'adapter_path': 'backend/build.py',
        'notes': 'iCE40HX-1k in TQ144 package. Onboard 12 MHz oscillator wired to global\nclock pin 21. Audio output goes to pad B1 (header J3 pin 1, package\npin 112). Programmed with `iceprog` over the on-board FT2232 USB-to-\nJTAG bridge.\n',
    },
    'tinyfpga-bx': {
        'id': 'tinyfpga-bx',
        'label': 'TinyFPGA BX',
        'kind': 'fpga-board',
        'chip_family': 'lp8k',
        'fpga_package': 'cm81',
        'clock_hz': 16000000,
        'clock_pin': 'B2',
        'audio_pin': 'A2',
        'flow': 'yosys-nextpnr-ice40',
        'free_for_open_source': True,
        'estimated_cost_usd': 40,
        'adapter_path': 'backend/build.py',
        'notes': 'iCE40LP-8k in CM81 package. Onboard 16 MHz oscillator at pad B2. Audio\noutput at pad A2 (GPIO connector pin 1). CM81 chipdbs use alphanumeric\npad names (vs the numeric pin numbers of TQ144/SG48). Programmed via\n`tinyprog` (USB bootloader; no external programmer needed).\n',
    },
    'icebreaker': {
        'id': 'icebreaker',
        'label': '1BitSquared iCEBreaker',
        'kind': 'fpga-board',
        'chip_family': 'up5k',
        'fpga_package': 'sg48',
        'clock_hz': 12000000,
        'clock_pin': '35',
        'audio_pin': '4',
        'vga_pins': {'vga_r': '43', 'vga_g': '38', 'vga_b': '34', 'vga_hsync': '31', 'vga_vsync': '42'},
        'flow': 'yosys-nextpnr-ice40',
        'free_for_open_source': True,
        'estimated_cost_usd': 70,
        'adapter_path': 'backend/build.py',
        'notes': "iCE40UP-5k in SG48 package. Onboard 12 MHz oscillator at global clock\npin 35. Audio output at PMOD1A pin 1 (package pin 4). VGA output\nrouted to PMOD1B pins per the 1BitSquared / Digilent VGA-PMOD\nconvention; pin map verified against amaranth_boards/icebreaker.py's\nPMOD1B connector string. 5280 LCs — comfortably bigger than iCEstick.\n",
    },
    'tt-pico': {
        'id': 'tt-pico',
        'label': 'Tiny Tapeout (Pico — 1x tile)',
        'kind': 'asic-shuttle',
        'pdk': 'sky130A',
        'package': 'caravel-mux',
        'flow': 'openlane-tt',
        'area': {'width_um': 150, 'height_um': 170, 'transistor_budget': 25000},
        'tiles': 1,
        'clock_hz': 50000000,
        'top_module_prefix': 'tt_um_',
        'submission': {'portal': 'https://app.tinytapeout.com', 'cohort': 'TTGF26a', 'cohort_closes': '2026-06-22', 'notes': 'TTSKY26a closed 2026-05-11; TTGF26a is the next open window.'},
        'free_for_open_source': True,
        'estimated_cost_usd': 0,
        'adapter_path': 'backend/tinytapeout.py',
        'notes': 'Existing Tiny Tapeout submission slot. 1x tile = ~150x170 um in\nsky130A. Designs live inside the eFabless Caravel multi-project\npin-mux wrapper as one user-project tile. Submitted via the Tiny\nTapeout portal; tape-out + packaging handled by the TT team.\nOpen-source designs get free slots via the Open Shuttle Program.\n',
    },
}

# Legacy aliases — older --target argument values mapped to current
# shuttle ids. Sprint 6 introduced 'ice40' as an alias for 'icestick';
# we preserve it so existing scripts / docs keep working unchanged.
ALIASES = {
    'ice40': 'icestick',
}

# PDK registry: id -> dict of fields straight from pdks.yaml.
PDKS = {
    'sky130A': {
        'id': 'sky130A',
        'label': 'SkyWater 130 nm Open PDK (variant A)',
        'vendor': 'SkyWater',
        'feature_size_nm': 130,
        'cell_library': 'sky130_fd_sc_hd',
        'cell_library_path': '$(PDK_ROOT)/sky130A/libs.ref/sky130_fd_sc_hd/verilog/',
        'pdk_root_env': 'PDK_ROOT',
        'default_pnr_tool': 'openlane',
        'default_density_target': 0.55,
        'open_source_license': 'Apache-2.0',
        'analog_capable': True,
        'notes': "The PDK most ChipBlocks users will encounter (via Tiny Tapeout's\neFabless shuttle). High-density 130 nm standard cells. Ships BJT\n+ diode models suitable for the analog frontend of an OOK\ntransmitter (planned S31). Has been the open-PDK reference since\nGoogle + SkyWater released it in 2020.\n",
    },
}

# Package registry: id -> dict of fields straight from packages.yaml.
PACKAGES = {
    'caravel-mux': {
        'id': 'caravel-mux',
        'label': 'eFabless Caravel multi-project pin-mux wrapper',
        'kind': 'wrapper',
        'total_pins': 38,
        'io_pins': {'ui_in': 8, 'uo_out': 8, 'uio': 8, 'control': 14},
        'upstream': 'https://github.com/efabless/caravel',
        'license': 'Apache-2.0',
        'notes': 'Standard wrapper for eFabless shuttle submissions. Tiny Tapeout\ndesigns live inside this wrapper as one mux-selected user-project\ntile. ui_in[0..7] = dedicated inputs; uo_out[0..7] = dedicated\noutputs; uio[0..7] = bidirectional (each has a direction bit in the\nCaravel io_oeb register).\n',
    },
}

# Build-flow registry: id -> dict of fields straight from flows.yaml.
FLOWS = {
    'yosys-nextpnr-ice40': {
        'id': 'yosys-nextpnr-ice40',
        'label': 'Yosys -> nextpnr-ice40 -> icepack',
        'target_kind': 'fpga-bitstream',
        'tools': [{'name': 'yosys', 'min_version': '0.30', 'license': 'ISC', 'install_hint': 'apt install yosys / OSS CAD Suite'}, {'name': 'nextpnr-ice40', 'min_version': '0.7', 'license': 'ISC', 'install_hint': 'apt install fpga-icestorm / OSS CAD Suite'}, {'name': 'icepack', 'min_version': '0.7', 'license': 'ISC', 'install_hint': 'apt install fpga-icestorm / OSS CAD Suite'}],
        'install_check': 'yosys -V && nextpnr-ice40 --version && icepack -V',
        'utilization_parser': 'backend/flows/yosys_nextpnr_ice40_parser.py',
        'adapter_path': 'backend/build.py',
        'notes': 'The fully-open FPGA bitstream flow. Permissively licensed all the\nway down (ISC for yosys / nextpnr-ice40 / icepack). Existing\nbuild.py implementation; the utilization parser at\nbackend/flows/yosys_nextpnr_ice40_parser.py is the post-Phase-0\nextraction of the ICESTORM_LC / SB_IO / SB_GB regex parsing that\ncurrently lives inline in build.py.\n',
    },
    'openlane-tt': {
        'id': 'openlane-tt',
        'label': 'OpenLane (Tiny Tapeout flow)',
        'target_kind': 'asic-submission-package',
        'tools': [{'name': 'openlane', 'min_version': '1.0', 'license': 'Apache-2.0', 'install_hint': 'Docker image efabless/openlane:current'}, {'name': 'magic', 'min_version': '8.3', 'license': 'GPL-2.0', 'install_hint': 'Used at the fab side; not bundled in shipped ChipBlocks'}],
        'install_check': 'true',
        'utilization_parser': 'backend/flows/openlane_parser.py',
        'adapter_path': 'backend/tinytapeout.py',
        'pdk_compatible': ['sky130A'],
        'notes': 'The submission-package flow for Tiny Tapeout. Note: OpenLane invokes\nMagic (GPL-2.0) at the fab side; we never bundle or redistribute\nMagic. The submission package contains only Verilog + info.yaml +\ncocotb testbench + LICENSE; the TT team / OpenLane run Magic on\ntheir side after we hand off the package.\n',
    },
}


def resolve_shuttle(target: str) -> dict | None:
    """Resolve a --target argument value to a shuttle row. Handles the
    legacy ALIASES map (e.g. 'ice40' -> 'icestick'). Returns None on
    unknown target — the caller is expected to friendly-error."""
    sid = ALIASES.get(target, target)
    return SHUTTLES.get(sid)
