// AUTO-GENERATED by scripts/codegen-manifests.mjs.
// Do not edit by hand. Run `npm run codegen:write` after editing
// shapes.yaml at repo root.
//
// Source: shapes.yaml + shapes.schema.json
// See ADR-006 + ADR-007 for the data model.

export const shapes = [
  {
    "id": "cylinder",
    "label": "Cylindrical region",
    "kind": "solid_region",
    "parameters_required": [
      {
        "name": "radius_mm",
        "units": "mm",
        "description": "Cylinder cross-section radius."
      },
      {
        "name": "length_mm",
        "units": "mm",
        "description": "Length along the cylinder axis."
      }
    ],
    "default_material_category": "resistive",
    "notes": "Classic through-hole resistor body geometry. Carbon-film / metal-film resistors. Also covers cylindrical capacitors (electrolytics) when the radius/length ratio is small."
  },
  {
    "id": "wire_path",
    "label": "Wire path",
    "kind": "wire_path",
    "parameters_required": [
      {
        "name": "width_mm",
        "units": "mm",
        "description": "Cross-section width (for rectangular trace)."
      },
      {
        "name": "thickness_um",
        "units": "um",
        "description": "Cross-section thickness."
      },
      {
        "name": "length_mm",
        "units": "mm",
        "description": "Path length along the wire."
      }
    ],
    "default_material_category": "conductor",
    "notes": "Generic conductive path. Used for wires, PCB traces, bond wires. Cross-section is rectangular (width × thickness); the path follows a 3D curve. For round-wire bonds, use width = diameter and the validator treats the cross-section as square-equivalent."
  },
  {
    "id": "plate",
    "label": "Plate (2D extent with thickness)",
    "kind": "plate",
    "parameters_required": [
      {
        "name": "area_shape",
        "units": "dimensionless",
        "description": "Outline: rectangle | circle | polygon."
      },
      {
        "name": "dimensions",
        "units": "mm",
        "description": "Outline parameters; depends on area_shape (e.g., {width, height} for rectangle)."
      },
      {
        "name": "thickness_um",
        "units": "um",
        "description": "Plate thickness."
      }
    ],
    "default_material_category": "conductor",
    "notes": "Used for capacitor plates, PCB ground/power planes, heatsink fins. The pair of conductive plates separated by a dielectric gap forms a parallel-plate capacitor."
  },
  {
    "id": "thin_film",
    "label": "Thin film",
    "kind": "thin_film",
    "parameters_required": [
      {
        "name": "thickness_um",
        "units": "um",
        "description": "Film thickness."
      },
      {
        "name": "area_mm2",
        "units": "mm2",
        "description": "Film area."
      }
    ],
    "default_material_category": "resistive",
    "notes": "Used for thin-film resistors (metal-film, carbon-film deposited on a ceramic substrate), thin-film capacitor dielectrics, sputtered metallization. Thickness is the load-bearing parameter — resistance is geometry × resistivity / thickness."
  },
  {
    "id": "gap",
    "label": "Gap (empty / dielectric space)",
    "kind": "gap",
    "parameters_required": [
      {
        "name": "thickness_um",
        "units": "um",
        "description": "Gap thickness (distance between bounding surfaces)."
      },
      {
        "name": "area_mm2",
        "units": "mm2",
        "description": "Gap area."
      }
    ],
    "default_material_category": "dielectric",
    "notes": "Used as the dielectric in capacitors (air, vacuum, oxide, polymer film), the space between PCB layers (filled with FR4 prepreg), or the breakdown-relevant separation between conductors. The 'material' that fills the gap is the dielectric — air, FR4, polyimide, etc."
  },
  {
    "id": "junction",
    "label": "Junction (semiconductor or contact)",
    "kind": "junction",
    "parameters_required": [
      {
        "name": "area_mm2",
        "units": "mm2",
        "description": "Junction area."
      },
      {
        "name": "depth_um",
        "units": "um",
        "description": "Junction depth (semiconductor) or interface thickness (contact)."
      }
    ],
    "default_material_category": "semiconductor",
    "notes": "Used for p-n junctions (diode, BJT base-emitter / base-collector), Schottky barriers (metal-semiconductor), and ohmic contacts. The geometric parameter set is minimal — semiconductor physics is encoded in Layer-3 behaviors, not Layer-1 shapes."
  },
  {
    "id": "hole",
    "label": "Hole / via",
    "kind": "hole",
    "parameters_required": [
      {
        "name": "diameter_mm",
        "units": "mm",
        "description": "Hole diameter."
      },
      {
        "name": "depth_mm",
        "units": "mm",
        "description": "Hole depth (through-hole = total board thickness; blind = partial)."
      }
    ],
    "default_material_category": "dielectric",
    "notes": "Used for vias (plated-through holes connecting PCB layers; the plating is a separate Layer-2 interface element), mounting holes, component through-hole leads. A plated via combines a Layer-1 hole + a Layer-1 wire_path inside it + a Layer-2 contact at each layer it touches."
  }
] as const

export type ShapesManifest = typeof shapes
