// Bundled example graphs accessible via the toolbar's Load → Examples
// menu. Same wire format as user-saved files, kept in sync with the
// canonical copies under <repo>/examples/. The renderer imports these
// at build time so they work in dev and packaged builds without IPC.

import type { Edge } from '@xyflow/react'
import type { AppNode } from './blocks'

export interface ExampleGraph {
  id: string
  label: string
  description: string
  nodes: AppNode[]
  edges: Edge[]
}

export const EXAMPLES: ExampleGraph[] = [
  {
    id: 'two-osc-mix',
    label: 'Two oscillators mixed',
    description: 'A 440 Hz square + 660 Hz saw averaged through a mixer.',
    nodes: [
      { id: 'osc1',  type: 'oscillator', position: { x: 50,  y: 60  }, data: { freq: 440 } },
      { id: 'osc2',  type: 'sawtooth',   position: { x: 50,  y: 220 }, data: { freq: 660 } },
      { id: 'mixer', type: 'mixer',      position: { x: 400, y: 130 }, data: {} },
      { id: 'out',   type: 'output',     position: { x: 700, y: 130 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'osc1',  target: 'mixer', sourceHandle: 'audio-out', targetHandle: 'in-1' },
      { id: 'e2', source: 'osc2',  target: 'mixer', sourceHandle: 'audio-out', targetHandle: 'in-2' },
      { id: 'e3', source: 'mixer', target: 'out',   sourceHandle: 'mix-out',   targetHandle: 'audio-in' },
    ],
  },
  {
    id: 'adsr-pulse',
    label: 'ADSR-shaped pulse',
    description: 'A square wave gated by a 4 Hz pulse, shaped by an Attack/Decay/Sustain/Release envelope.',
    nodes: [
      { id: 'osc',  type: 'oscillator', position: { x: 50,  y: 60  }, data: { freq: 440 } },
      { id: 'gate', type: 'gate',       position: { x: 50,  y: 220 }, data: { rate_hz: 4, duty_pct: 50 } },
      { id: 'env',  type: 'adsr',       position: { x: 350, y: 80  }, data: { attack_ms: 20, decay_ms: 80, sustain_level: 80, release_ms: 150 } },
      { id: 'out',  type: 'output',     position: { x: 700, y: 130 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'osc',  target: 'env', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
      { id: 'e2', source: 'gate', target: 'env', sourceHandle: 'gate-out',  targetHandle: 'gate'     },
      { id: 'e3', source: 'env',  target: 'out', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
    ],
  },
  {
    id: 'kick-drum',
    label: 'Kick drum',
    description: 'A 60 Hz sine pulsed by a fast-decay envelope — short low-frequency thump.',
    nodes: [
      { id: 'sine', type: 'sine',   position: { x: 50,  y: 60  }, data: { freq: 60 } },
      { id: 'gate', type: 'gate',   position: { x: 50,  y: 220 }, data: { rate_hz: 2, duty_pct: 5 } },
      { id: 'env',  type: 'adsr',   position: { x: 400, y: 80  }, data: { attack_ms: 1, decay_ms: 80, sustain_level: 0, release_ms: 1 } },
      { id: 'out',  type: 'output', position: { x: 700, y: 130 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'sine', target: 'env', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
      { id: 'e2', source: 'gate', target: 'env', sourceHandle: 'gate-out',  targetHandle: 'gate'     },
      { id: 'e3', source: 'env',  target: 'out', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
    ],
  },
  {
    id: 'snare-drum',
    label: 'Snare drum',
    description: 'A noise burst gated by a fast-decay envelope — classic snare crack.',
    nodes: [
      { id: 'noise', type: 'noise',  position: { x: 50,  y: 60  }, data: {} },
      { id: 'gate',  type: 'gate',   position: { x: 50,  y: 220 }, data: { rate_hz: 2, duty_pct: 5 } },
      { id: 'env',   type: 'adsr',   position: { x: 400, y: 80  }, data: { attack_ms: 1, decay_ms: 60, sustain_level: 0, release_ms: 1 } },
      { id: 'out',   type: 'output', position: { x: 700, y: 130 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'noise', target: 'env', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
      { id: 'e2', source: 'gate',  target: 'env', sourceHandle: 'gate-out',  targetHandle: 'gate'     },
      { id: 'e3', source: 'env',   target: 'out', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
    ],
  },
  {
    id: 'bass-lead',
    label: 'Bass lead',
    description: 'A 110 Hz sawtooth low-pass filtered, then gated by a sustaining envelope — punchy bass line.',
    nodes: [
      { id: 'saw',  type: 'sawtooth', position: { x: 50,  y: 60  }, data: { freq: 110 } },
      { id: 'gate', type: 'gate',     position: { x: 50,  y: 380 }, data: { rate_hz: 2, duty_pct: 50 } },
      { id: 'lpf',  type: 'lowpass',  position: { x: 350, y: 60  }, data: { cutoff_hz: 600 } },
      { id: 'env',  type: 'adsr',     position: { x: 600, y: 80  }, data: { attack_ms: 5, decay_ms: 40, sustain_level: 100, release_ms: 100 } },
      { id: 'out',  type: 'output',   position: { x: 900, y: 130 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'saw',  target: 'lpf', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
      { id: 'e2', source: 'lpf',  target: 'env', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
      { id: 'e3', source: 'gate', target: 'env', sourceHandle: 'gate-out',  targetHandle: 'gate'     },
      { id: 'e4', source: 'env',  target: 'out', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
    ],
  },
  {
    id: 'lofi-pad',
    label: 'Lo-fi pad',
    description: 'Two triangles a major-third apart (220 + 277 Hz), mixed and softly low-passed — sustained drone.',
    nodes: [
      { id: 'tri1',  type: 'triangle', position: { x: 50,  y: 60  }, data: { freq: 220 } },
      { id: 'tri2',  type: 'triangle', position: { x: 50,  y: 220 }, data: { freq: 277 } },
      { id: 'mixer', type: 'mixer',    position: { x: 350, y: 130 }, data: {} },
      { id: 'lpf',   type: 'lowpass',  position: { x: 600, y: 130 }, data: { cutoff_hz: 1500 } },
      { id: 'out',   type: 'output',   position: { x: 900, y: 130 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'tri1',  target: 'mixer', sourceHandle: 'audio-out', targetHandle: 'in-1'     },
      { id: 'e2', source: 'tri2',  target: 'mixer', sourceHandle: 'audio-out', targetHandle: 'in-2'     },
      { id: 'e3', source: 'mixer', target: 'lpf',   sourceHandle: 'mix-out',   targetHandle: 'audio-in' },
      { id: 'e4', source: 'lpf',   target: 'out',   sourceHandle: 'audio-out', targetHandle: 'audio-in' },
    ],
  },
  {
    id: 'arpeggio',
    label: 'Stair-stepped arpeggio',
    description: 'A slow 4 Hz sawtooth sampled by an 8 Hz clock — sample-and-hold turns the ramp into a quantized note sequence.',
    nodes: [
      { id: 'saw',  type: 'sawtooth',   position: { x: 50,  y: 60  }, data: { freq: 4 } },
      { id: 'gate', type: 'gate',       position: { x: 50,  y: 220 }, data: { rate_hz: 8, duty_pct: 50 } },
      { id: 'snh',  type: 'samplehold', position: { x: 400, y: 130 }, data: {} },
      { id: 'out',  type: 'output',     position: { x: 700, y: 130 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'saw',  target: 'snh', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
      { id: 'e2', source: 'gate', target: 'snh', sourceHandle: 'gate-out',  targetHandle: 'clock'    },
      { id: 'e3', source: 'snh',  target: 'out', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
    ],
  },
  {
    id: 'echo',
    label: 'Echo',
    description: 'Direct + delayed signal mixed; the delayed copy is scaled to half-amplitude via Multiply by Constant 64. Demonstrates Delay + Multiply + Mixer composition.',
    nodes: [
      { id: 'src',   type: 'oscillator', position: { x: 50,   y: 60  }, data: { freq: 220 } },
      { id: 'delay', type: 'delay',      position: { x: 350,  y: 220 }, data: { delay_samples: 256 } },
      { id: 'scale', type: 'constant',   position: { x: 350,  y: 380 }, data: { value: 64 } },
      { id: 'wet',   type: 'multiply',   position: { x: 600,  y: 300 }, data: {} },
      { id: 'mix',   type: 'mixer',      position: { x: 850,  y: 180 }, data: {} },
      { id: 'out',   type: 'output',     position: { x: 1100, y: 180 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'src',   target: 'mix',   sourceHandle: 'audio-out', targetHandle: 'in-1'     },
      { id: 'e2', source: 'src',   target: 'delay', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
      { id: 'e3', source: 'delay', target: 'wet',   sourceHandle: 'audio-out', targetHandle: 'in-1'     },
      { id: 'e4', source: 'scale', target: 'wet',   sourceHandle: 'audio-out', targetHandle: 'in-2'     },
      { id: 'e5', source: 'wet',   target: 'mix',   sourceHandle: 'audio-out', targetHandle: 'in-2'     },
      { id: 'e6', source: 'mix',   target: 'out',   sourceHandle: 'mix-out',   targetHandle: 'audio-in' },
    ],
  },
  {
    id: 'lofi-crunch',
    label: 'Lo-fi crunch',
    description: 'A 220 Hz sawtooth bit-crushed to 3 effective bits, then softened with a low-pass at 2 kHz — gritty retro tone.',
    nodes: [
      { id: 'saw',    type: 'sawtooth',   position: { x: 50,  y: 130 }, data: { freq: 220 } },
      { id: 'crunch', type: 'bitcrusher', position: { x: 350, y: 130 }, data: { bits: 3 } },
      { id: 'smooth', type: 'lowpass',    position: { x: 600, y: 130 }, data: { cutoff_hz: 2000 } },
      { id: 'out',    type: 'output',     position: { x: 850, y: 130 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'saw',    target: 'crunch', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
      { id: 'e2', source: 'crunch', target: 'smooth', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
      { id: 'e3', source: 'smooth', target: 'out',    sourceHandle: 'audio-out', targetHandle: 'audio-in' },
    ],
  },
  {
    id: 'color-bars',
    label: 'Color bars on a VGA monitor',
    description: 'VGA Timing → Color Bars → VGA Output. The first visual chip: build to iCEBreaker, plug a VGA-PMOD into PMOD1B, see 8 SMPTE color bars.',
    nodes: [
      { id: 'vt', type: 'vgatiming', position: { x: 50,  y: 60 }, data: {} },
      { id: 'cb', type: 'colorbars', position: { x: 380, y: 60 }, data: {} },
      { id: 'vo', type: 'vgaoutput', position: { x: 700, y: 60 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'vt', target: 'cb', sourceHandle: 'x',       targetHandle: 'x'       },
      { id: 'e2', source: 'vt', target: 'cb', sourceHandle: 'visible', targetHandle: 'visible' },
      { id: 'e3', source: 'cb', target: 'vo', sourceHandle: 'r',       targetHandle: 'r'       },
      { id: 'e4', source: 'cb', target: 'vo', sourceHandle: 'g',       targetHandle: 'g'       },
      { id: 'e5', source: 'cb', target: 'vo', sourceHandle: 'b',       targetHandle: 'b'       },
      { id: 'e6', source: 'vt', target: 'vo', sourceHandle: 'hsync',   targetHandle: 'hsync'   },
      { id: 'e7', source: 'vt', target: 'vo', sourceHandle: 'vsync',   targetHandle: 'vsync'   },
    ],
  },
  {
    id: 'vga-stripe',
    label: 'White vertical stripe on a VGA monitor',
    description: 'VGA Timing → Pixel Range → VGA Output. The Pixel Range output drives all three R/G/B channels, so the in-window pixels paint white on a black background. v0.1 has no visual mixer, so background-and-foreground rectangles need a future block — this is the simplest patch the visual chain currently supports.',
    nodes: [
      { id: 'vt', type: 'vgatiming',  position: { x: 50,  y: 60 }, data: {} },
      { id: 'pr', type: 'pixelrange', position: { x: 380, y: 60 }, data: { start: 100, end: 200 } },
      { id: 'vo', type: 'vgaoutput',  position: { x: 700, y: 60 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'vt', target: 'pr', sourceHandle: 'x',      targetHandle: 'pixel'  },
      { id: 'e2', source: 'pr', target: 'vo', sourceHandle: 'inside', targetHandle: 'r'      },
      { id: 'e3', source: 'pr', target: 'vo', sourceHandle: 'inside', targetHandle: 'g'      },
      { id: 'e4', source: 'pr', target: 'vo', sourceHandle: 'inside', targetHandle: 'b'      },
      { id: 'e5', source: 'vt', target: 'vo', sourceHandle: 'hsync',  targetHandle: 'hsync'  },
      { id: 'e6', source: 'vt', target: 'vo', sourceHandle: 'vsync',  targetHandle: 'vsync'  },
    ],
  },
  {
    id: 'cpu-accumulator',
    label: 'CPU accumulator (Counter→ROM→Adder→Register, audio via Reinterpret)',
    description: 'A tiny accumulator using the Sprint 17 CPU primitives: a Counter walks a 16-entry ROM (the first 8 Fibonacci numbers, padded with zeros), the ROM byte feeds Adder.in-a, a Register holds the running sum and feeds it back via Adder.in-b, and a parallel RAM logs each new sum to the same address. The Sprint 18 Reinterpret block bridges the CPU-domain Register output (data-u8) to the audio domain (audio-s8) so the running sum actually drives the speaker — the LSBs of the sum vary per cycle, producing rhythmic crackle.',
    nodes: [
      { id: 'gate', type: 'gate',        position: { x: 40,   y: 60  }, data: { rate_hz: 100, duty_pct: 50 } },
      { id: 'cnt',  type: 'counter',     position: { x: 240,  y: 60  }, data: { max_value: 16 } },
      { id: 'rom',  type: 'rom',         position: { x: 460,  y: 60  }, data: { contents: [1, 1, 2, 3, 5, 8, 13, 21, 0, 0, 0, 0, 0, 0, 0, 0] } },
      { id: 'add',  type: 'adder',       position: { x: 720,  y: 60  }, data: {} },
      { id: 'reg',  type: 'register',    position: { x: 940,  y: 60  }, data: {} },
      { id: 'ram',  type: 'ram',         position: { x: 720,  y: 280 }, data: {} },
      { id: 'ri',   type: 'reinterpret', position: { x: 940,  y: 320 }, data: {} },
      { id: 'out',  type: 'output',      position: { x: 1140, y: 320 }, data: {} },
    ],
    edges: [
      { id: 'e1',  source: 'gate', target: 'cnt', sourceHandle: 'gate-out',  targetHandle: 'clock'        },
      { id: 'e2',  source: 'cnt',  target: 'rom', sourceHandle: 'addr-out',  targetHandle: 'addr'         },
      { id: 'e3',  source: 'rom',  target: 'add', sourceHandle: 'data-out',  targetHandle: 'in-a'         },
      { id: 'e4',  source: 'reg',  target: 'add', sourceHandle: 'data-out',  targetHandle: 'in-b'         },
      { id: 'e5',  source: 'add',  target: 'reg', sourceHandle: 'sum-out',   targetHandle: 'data-in'      },
      { id: 'e6',  source: 'gate', target: 'reg', sourceHandle: 'gate-out',  targetHandle: 'write-enable' },
      { id: 'e7',  source: 'cnt',  target: 'ram', sourceHandle: 'addr-out',  targetHandle: 'addr'         },
      { id: 'e8',  source: 'reg',  target: 'ram', sourceHandle: 'data-out',  targetHandle: 'data-in'      },
      { id: 'e9',  source: 'gate', target: 'ram', sourceHandle: 'gate-out',  targetHandle: 'write-enable' },
      { id: 'e10', source: 'reg',  target: 'ri',  sourceHandle: 'data-out',  targetHandle: 'data-in'      },
      { id: 'e11', source: 'ri',   target: 'out', sourceHandle: 'audio-out', targetHandle: 'audio-in'     },
    ],
  },
  {
    id: 'cpu-counter-with-branch',
    label: 'Branchable counter (Comparator + Mux conditional reset)',
    description: 'A counter that resets at a target value — a tiny program that branches without a state machine. Three ByteConstants supply the literal values (1 to increment, 7 as the reset target, 0 as the reset value); no Counter or ROM needed since the values never change. Each cycle: Adder adds the increment to the Register; Comparator checks whether the Register equals the target; Mux picks between the incremented sum and 0 based on the equal flag; the chosen value latches on the gate edge. Output runs through Reinterpret so the running counter (0..7..0..7..) is audible as a saw-shaped buzz. (Refactored in Sprint 20 from 3 single-value ROMs + a redundant Counter to 3 ByteConstants — same behavior, 4 fewer blocks.)',
    nodes: [
      { id: 'gate',      type: 'gate',         position: { x: 40,   y: 200 }, data: { rate_hz: 200, duty_pct: 50 } },
      { id: 'bc_inc',    type: 'byteconstant', position: { x: 280,  y: 40  }, data: { value: 1 } },
      { id: 'bc_target', type: 'byteconstant', position: { x: 280,  y: 220 }, data: { value: 7 } },
      { id: 'bc_reset',  type: 'byteconstant', position: { x: 280,  y: 400 }, data: { value: 0 } },
      { id: 'add',       type: 'adder',        position: { x: 540,  y: 60  }, data: {} },
      { id: 'cmp',       type: 'comparator',   position: { x: 540,  y: 240 }, data: {} },
      { id: 'mux',       type: 'mux',          position: { x: 760,  y: 200 }, data: {} },
      { id: 'reg',       type: 'register',     position: { x: 980,  y: 200 }, data: {} },
      { id: 'ri',        type: 'reinterpret',  position: { x: 1200, y: 200 }, data: {} },
      { id: 'out',       type: 'output',       position: { x: 1400, y: 200 }, data: {} },
    ],
    edges: [
      { id: 'e1',  source: 'bc_inc',    target: 'add', sourceHandle: 'data-out',  targetHandle: 'in-a'         },
      { id: 'e2',  source: 'reg',       target: 'add', sourceHandle: 'data-out',  targetHandle: 'in-b'         },
      { id: 'e3',  source: 'reg',       target: 'cmp', sourceHandle: 'data-out',  targetHandle: 'in-a'         },
      { id: 'e4',  source: 'bc_target', target: 'cmp', sourceHandle: 'data-out',  targetHandle: 'in-b'         },
      { id: 'e5',  source: 'add',       target: 'mux', sourceHandle: 'sum-out',   targetHandle: 'in-a'         },
      { id: 'e6',  source: 'bc_reset',  target: 'mux', sourceHandle: 'data-out',  targetHandle: 'in-b'         },
      { id: 'e7',  source: 'cmp',       target: 'mux', sourceHandle: 'eq-out',    targetHandle: 'select'       },
      { id: 'e8',  source: 'mux',       target: 'reg', sourceHandle: 'data-out',  targetHandle: 'data-in'      },
      { id: 'e9',  source: 'gate',      target: 'reg', sourceHandle: 'gate-out',  targetHandle: 'write-enable' },
      { id: 'e10', source: 'reg',       target: 'ri',  sourceHandle: 'data-out',  targetHandle: 'data-in'      },
      { id: 'e11', source: 'ri',        target: 'out', sourceHandle: 'audio-out', targetHandle: 'audio-in'     },
    ],
  },
  {
    id: 'vibrato',
    label: 'Vibrato (LFO modulating a VCO at canonical 6 Hz)',
    description: 'The canonical use case for the Sprint 24 VCO block, now using the Sprint 24 LFO block at 6 Hz — the textbook vibrato rate. A 6 Hz sine LFO drives the VCO\'s freq-in port; the VCO outputs a 440 Hz square that sweeps ±15 Hz around centre 6 times per second. The result is a singing vibrato wobble. (Earlier revision used a 20 Hz sine oscillator since the audio-frequency sine block bottoms out at 20 Hz; the LFO block solves that by going as low as 1 Hz.) Demonstrates the LFO + VCO combination as the building block for all kinds of audio-rate-controlled-pitch synthesis.',
    nodes: [
      { id: 'lfo', type: 'lfo',    position: { x: 60,  y: 80 }, data: { rate: 6, shape: 'sine' } },
      { id: 'vco', type: 'vco',    position: { x: 360, y: 80 }, data: { base_freq: 440, range: 15 } },
      { id: 'out', type: 'output', position: { x: 660, y: 80 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'lfo', target: 'vco', sourceHandle: 'audio-out', targetHandle: 'freq-in' },
      { id: 'e2', source: 'vco', target: 'out', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
    ],
  },
  {
    id: 'karplus-strong',
    label: 'Karplus-Strong plucked string (1983 Stanford algorithm, ringing variant)',
    description: 'Implements the Karplus-Strong plucked-string synthesis algorithm published by Kevin Karplus and Alex Strong, Computer Music Journal Vol. 7 No. 2 (1983). US patents 4,649,783 + 4,622,877 (Stanford) expired 2004 / 2005; algorithm is now freely usable. A gated noise burst excites a feedback loop: AudioSum (saturating, no averaging) → delay → lowpass → multiply (× Constant 125 ≈ 0.977 feedback gain) → back into AudioSum. The delay length sets the pitch (400 samples → 110 Hz at 44.1 kHz). The lowpass simulates the natural string damping. The Constant + Multiply pair sets per-loop gain to about 0.977, which gives ~400-500 ms of audible decay — the canonical ringing-string sound. (An earlier Sprint 23 revision used Mixer in the feedback loop, which halved amplitude per cycle and decayed in ~60 ms; the Sprint 24 AudioSum block exists precisely so this graph can reach the textbook ringing version.)',
    nodes: [
      { id: 'noise',         type: 'noise',    position: { x: 60,   y: 80  }, data: {} },
      { id: 'gate',          type: 'gate',     position: { x: 60,   y: 360 }, data: { rate_hz: 2, duty_pct: 1 } },
      { id: 'pluck_env',     type: 'adsr',     position: { x: 320,  y: 200 }, data: { attack_ms: 1, decay_ms: 5, sustain_level: 0, release_ms: 1 } },
      { id: 'sum',           type: 'audiosum', position: { x: 600,  y: 200 }, data: {} },
      { id: 'delay',         type: 'delay',    position: { x: 860,  y: 200 }, data: { delay_samples: 400 } },
      { id: 'lowpass',       type: 'lowpass',  position: { x: 860,  y: 380 }, data: { cutoff_hz: 4000 } },
      { id: 'feedback_gain', type: 'constant', position: { x: 600,  y: 380 }, data: { value: 125 } },
      { id: 'fb_mult',       type: 'multiply', position: { x: 600,  y: 500 }, data: {} },
      { id: 'out',           type: 'output',   position: { x: 1120, y: 200 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'noise',         target: 'pluck_env', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
      { id: 'e2', source: 'gate',          target: 'pluck_env', sourceHandle: 'gate-out',  targetHandle: 'gate'     },
      { id: 'e3', source: 'pluck_env',     target: 'sum',       sourceHandle: 'audio-out', targetHandle: 'in-1'     },
      { id: 'e4', source: 'lowpass',       target: 'fb_mult',   sourceHandle: 'audio-out', targetHandle: 'in-1'     },
      { id: 'e5', source: 'feedback_gain', target: 'fb_mult',   sourceHandle: 'audio-out', targetHandle: 'in-2'     },
      { id: 'e6', source: 'fb_mult',       target: 'sum',       sourceHandle: 'audio-out', targetHandle: 'in-2'     },
      { id: 'e7', source: 'sum',           target: 'delay',     sourceHandle: 'audio-out', targetHandle: 'audio-in' },
      { id: 'e8', source: 'delay',         target: 'lowpass',   sourceHandle: 'audio-out', targetHandle: 'audio-in' },
      { id: 'e9', source: 'sum',           target: 'out',       sourceHandle: 'audio-out', targetHandle: 'audio-in' },
    ],
  },
  {
    id: 'divider-clock-tree',
    label: 'Frequency divider tree (two counters dividing one master clock)',
    description: 'A 1000 Hz master clock (Gate at maximum rate, 50% duty) drives two counters in parallel. Counter 1 has max_value 8 → its centred audio-out is a sawtooth at 1000/8 = 125 Hz. Counter 2 has max_value 64 → audio-out is a slower sawtooth at 1000/64 ≈ 15.6 Hz. Summed via AudioSum (so each contributes full amplitude), the output is a polyrhythmic stack of two divided rates. Demonstrates the textbook binary-ripple-counter pattern (74HC4040 family, 1970s): every digital chip on Earth uses divider chains to derive slower clocks from a fast master. (A richer multi-stage tree with per-bit individual square-wave outputs is deferred — would need either widened bussplit (to accept addr-u4) or an audio-to-gate comparator block. The 2-counter version here captures the conceptual core.)',
    nodes: [
      { id: 'master_clock', type: 'gate',     position: { x: 60,  y: 200 }, data: { rate_hz: 1000, duty_pct: 50 } },
      { id: 'divider_8',    type: 'counter',  position: { x: 320, y: 80  }, data: { max_value: 8 } },
      { id: 'divider_64',   type: 'counter',  position: { x: 320, y: 320 }, data: { max_value: 64 } },
      { id: 'mixer',        type: 'audiosum', position: { x: 600, y: 200 }, data: {} },
      { id: 'out',          type: 'output',   position: { x: 860, y: 200 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'master_clock', target: 'divider_8',  sourceHandle: 'gate-out',  targetHandle: 'clock'    },
      { id: 'e2', source: 'master_clock', target: 'divider_64', sourceHandle: 'gate-out',  targetHandle: 'clock'    },
      { id: 'e3', source: 'divider_8',    target: 'mixer',      sourceHandle: 'audio-out', targetHandle: 'in-1'     },
      { id: 'e4', source: 'divider_64',   target: 'mixer',      sourceHandle: 'audio-out', targetHandle: 'in-2'     },
      { id: 'e5', source: 'mixer',        target: 'out',        sourceHandle: 'audio-out', targetHandle: 'audio-in' },
    ],
  },
  {
    id: 'hihat',
    label: 'Hi-hat (filtered noise + fast envelope)',
    description: 'Standard subtractive-synthesis hi-hat: white noise through a narrow band-pass filter centered at 7100 Hz (the metallic "tsss" frequency range, classic TR-808-era parameter) gated by a fast-decay ADSR envelope (attack 1ms, decay 50ms, sustain 0, release 10ms). Combined with the existing kick-drum.json and snare-drum.json, this completes the kick + snare + hat trilogy — the foundation of nearly all rhythm-based music. Generic analog-modular technique predating consumer electronics; no specific authorship to credit. Not affiliated with Roland or any drum-machine manufacturer.',
    nodes: [
      { id: 'noise',  type: 'noise',    position: { x: 60,  y: 80  }, data: {} },
      { id: 'filter', type: 'bandpass', position: { x: 280, y: 80  }, data: { center_hz: 7100 } },
      { id: 'gate',   type: 'gate',     position: { x: 60,  y: 240 }, data: { rate_hz: 4, duty_pct: 5 } },
      { id: 'env',    type: 'adsr',     position: { x: 540, y: 160 }, data: { attack_ms: 1, decay_ms: 50, sustain_level: 0, release_ms: 10 } },
      { id: 'out',    type: 'output',   position: { x: 820, y: 160 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'noise',  target: 'filter', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
      { id: 'e2', source: 'filter', target: 'env',    sourceHandle: 'audio-out', targetHandle: 'audio-in' },
      { id: 'e3', source: 'gate',   target: 'env',    sourceHandle: 'gate-out',  targetHandle: 'gate'     },
      { id: 'e4', source: 'env',    target: 'out',    sourceHandle: 'audio-out', targetHandle: 'audio-in' },
    ],
  },
  {
    id: 'fm-bell',
    label: 'FM bell (Chowning two-operator, post-1994 patent-expired)',
    description: 'Two-operator FM synthesis as published by John M. Chowning, Journal of the Audio Engineering Society Vol. 21 No. 7 (1973). US patent 4,018,121 (Stanford, exclusively licensed to Yamaha for decades) expired April 1994; algorithm is now freely usable. Carrier 440 Hz; modulator at 616 Hz (carrier × 1.4, the non-integer ratio that produces inharmonic bell-like partials); modulation depth 90 for a bright bell timbre. Gate triggers ADSR envelope (attack 1ms, decay 200ms, sustain 0, release 2000ms) — the long release is what makes a bell ring. NOT affiliated with Yamaha; the DX7 used the same patent but a different preset.',
    nodes: [
      { id: 'gate',     type: 'gate',   position: { x: 60,  y: 240 }, data: { rate_hz: 1, duty_pct: 5 } },
      { id: 'fm_voice', type: 'fm',     position: { x: 60,  y: 80  }, data: { carrier_freq: 440, modulator_freq: 616, mod_depth: 90 } },
      { id: 'env',      type: 'adsr',   position: { x: 380, y: 160 }, data: { attack_ms: 1, decay_ms: 200, sustain_level: 0, release_ms: 2000 } },
      { id: 'out',      type: 'output', position: { x: 700, y: 160 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'fm_voice', target: 'env', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
      { id: 'e2', source: 'gate',     target: 'env', sourceHandle: 'gate-out',  targetHandle: 'gate'     },
      { id: 'e3', source: 'env',      target: 'out', sourceHandle: 'audio-out', targetHandle: 'audio-in' },
    ],
  },
  {
    id: 'atari-punk-console',
    label: 'Atari Punk Console (1980 stepped-tone generator)',
    description: 'Inspired by Forrest M. Mims III\'s 1980 "Stepped Tone Generator" from Engineer\'s Notebook: Integrated Circuit Applications (Radio Shack). A 220 Hz audio oscillator is gated by a 5 Hz LFO (square wave) — the slower waveform chops the faster one into the famous rhythmic burble, the "DIY-synth-101" sound. Now uses the Sprint 24 LFO block (1-30 Hz range) for the gating; an earlier revision used a 20 Hz oscillator at the lower bound of the audio range, which produced a faster wobble than Mims\'s pot-swept original (Mims swept 1-30 Hz on a potentiometer). ChipBlocks reproduces the topology only; the original is an analog 555-timer circuit. Provenance + license in CREDITS.md (555 patent US 3,652,888 expired 1988; circuit topology not copyrightable).',
    nodes: [
      { id: 'audio_osc', type: 'oscillator', position: { x: 60,  y: 80  }, data: { freq: 220 } },
      { id: 'gate_osc',  type: 'lfo',        position: { x: 60,  y: 240 }, data: { rate: 5, shape: 'square' } },
      { id: 'mult',      type: 'multiply',   position: { x: 340, y: 160 }, data: {} },
      { id: 'out',       type: 'output',     position: { x: 600, y: 160 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'audio_osc', target: 'mult', sourceHandle: 'audio-out', targetHandle: 'in-1'     },
      { id: 'e2', source: 'gate_osc',  target: 'mult', sourceHandle: 'audio-out', targetHandle: 'in-2'     },
      { id: 'e3', source: 'mult',      target: 'out',  sourceHandle: 'audio-out', targetHandle: 'audio-in' },
    ],
  },
  {
    id: 'cpu-multiregister',
    label: 'Register File multi-port (independent read / write addresses)',
    description: 'Demonstrates the Sprint 20 Register File block — same storage shape as RAM, but read and write addresses are independent. A fast Counter (sweeping all 16 registers) drives `read-addr` while a slower Counter (sweeping the first 4) drives `write-addr`. A small ROM feeds `data-in`, so registers 0..3 get continuously refreshed with the ROM ramp (16, 48, 80, 112) while registers 4..15 stay zero. The read sweep produces a 4-step ramp followed by 12 zero cells, audible at ~12 Hz through Reinterpret. Compare with cpu-accumulator (RAM) — same wiring shape, but here read-addr and write-addr move independently. The canonical CPU register-file pattern: read one register while writing another in the same cycle.',
    nodes: [
      { id: 'gate',      type: 'gate',         position: { x: 40,   y: 60  }, data: { rate_hz: 200, duty_pct: 50 } },
      { id: 'cnt_read',  type: 'counter',      position: { x: 260,  y: 40  }, data: { max_value: 16 } },
      { id: 'cnt_write', type: 'counter',      position: { x: 260,  y: 220 }, data: { max_value: 4 } },
      { id: 'rom',       type: 'rom',          position: { x: 500,  y: 220 }, data: { contents: [16, 48, 80, 112, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } },
      { id: 'rf',        type: 'registerfile', position: { x: 760,  y: 100 }, data: {} },
      { id: 'ri',        type: 'reinterpret',  position: { x: 1020, y: 140 }, data: {} },
      { id: 'out',       type: 'output',       position: { x: 1220, y: 140 }, data: {} },
    ],
    edges: [
      { id: 'e1', source: 'gate',      target: 'cnt_read',  sourceHandle: 'gate-out',  targetHandle: 'clock'        },
      { id: 'e2', source: 'gate',      target: 'cnt_write', sourceHandle: 'gate-out',  targetHandle: 'clock'        },
      { id: 'e3', source: 'cnt_write', target: 'rom',       sourceHandle: 'addr-out',  targetHandle: 'addr'         },
      { id: 'e4', source: 'cnt_read',  target: 'rf',        sourceHandle: 'addr-out',  targetHandle: 'read-addr'    },
      { id: 'e5', source: 'cnt_write', target: 'rf',        sourceHandle: 'addr-out',  targetHandle: 'write-addr'   },
      { id: 'e6', source: 'rom',       target: 'rf',        sourceHandle: 'data-out',  targetHandle: 'data-in'      },
      { id: 'e7', source: 'gate',      target: 'rf',        sourceHandle: 'gate-out',  targetHandle: 'write-enable' },
      { id: 'e8', source: 'rf',        target: 'ri',        sourceHandle: 'data-out',  targetHandle: 'data-in'      },
      { id: 'e9', source: 'ri',        target: 'out',       sourceHandle: 'audio-out', targetHandle: 'audio-in'     },
    ],
  },
]
