#!/usr/bin/env python3
"""codegen-backend.py — Phase 0 scaffolding for ADR-003 block manifest.

Reads blocks.yaml + blocks.schema.json at repo root, validates the
manifest, and emits fragments for 2 backend target files:

  1. backend/blocks/__init__.py        — imports + BLOCK_REGISTRY + __all__
  2. backend/blocks/_params_gen.py     — NEW file; build_params(node_type, data)

Modes:
  --check (default) — extract live sections from __init__.py via anchor
                      regex and the (not-yet-existing) _params_gen.py as
                      a whole-file generated artifact, byte-diff against
                      generated output, exit non-zero with a unified diff
                      if any diverge. _params_gen.py is whole-file codegen
                      because the file does not exist yet — its byte diff
                      compares against an empty string until Phase 1.
  --write           — Phase 1 only; not used in Phase 0.

Boundary detection per target:
  __init__.py:
    imports        — first/last `from .<module> import <Class>` line.
    BLOCK_REGISTRY — `BLOCK_REGISTRY = {` to the matching `}`.
    __all__        — `__all__ = [` to the matching `]`.
  _params_gen.py:  whole-file (does not exist in Phase 0).

Install (both MIT-licensed):
  pip install pyyaml jsonschema

Invocation:
  python3 scripts/codegen-backend.py            # --check (default)
  python3 scripts/codegen-backend.py --write    # Phase 1 only

Phase 0 contract: --check exits 0 iff every target file's extracted
section is byte-identical to the corresponding generated fragment.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / 'blocks.yaml'
SCHEMA = REPO_ROOT / 'blocks.schema.json'


def _load_manifest():
    try:
        import yaml
        import jsonschema
    except ImportError as exc:
        sys.stderr.write(
            '[codegen-backend] missing dependency: '
            f'{exc.name}. Install with `pip install pyyaml jsonschema`.\n'
        )
        sys.exit(2)

    if not MANIFEST.exists():
        sys.stderr.write(f'[codegen-backend] blocks.yaml not found at {MANIFEST}\n')
        sys.stderr.write(
            '  Phase 0 step 1 (manifest authoring) has to land first.\n'
        )
        sys.exit(2)
    if not SCHEMA.exists():
        sys.stderr.write(f'[codegen-backend] blocks.schema.json not found\n')
        sys.exit(2)

    import json
    manifest = yaml.safe_load(MANIFEST.read_text(encoding='utf-8'))
    schema = json.loads(SCHEMA.read_text(encoding='utf-8'))
    validator = jsonschema.Draft7Validator(schema)
    errors = sorted(validator.iter_errors(manifest), key=lambda e: list(e.absolute_path))
    if errors:
        sys.stderr.write('[codegen-backend] blocks.yaml fails schema validation:\n')
        for err in errors:
            path = '/'.join(str(p) for p in err.absolute_path) or '<root>'
            sys.stderr.write(f'  {path}: {err.message}\n')
        sys.exit(2)
    return manifest


def _module_name(backend_path: str) -> str:
    """`backend/blocks/sample_and_hold.py` -> `sample_and_hold`."""
    return Path(backend_path).stem


# ────────────────────────────────────────────────────────────────────────────
# Fragment generators
# ────────────────────────────────────────────────────────────────────────────


def gen_init_imports(manifest) -> str:
    """One `from .module import Class` line per block, manifest order."""
    return '\n'.join(
        f'from .{_module_name(b["backendPath"])} import {b["backendClass"]}'
        for b in manifest
    )


def gen_init_registry(manifest) -> str:
    """The BLOCK_REGISTRY dict body — opening brace to closing brace."""
    rows = [f'    "{b["type"]}": {b["backendClass"]},' for b in manifest]
    return '# Registry mapping graph node `type` (from React Flow JSON) to block class.\nBLOCK_REGISTRY = {\n' + '\n'.join(rows) + '\n}'


def gen_init_all(manifest) -> str:
    """The __all__ list body."""
    entries = [f'    "{b["backendClass"]}",' for b in manifest]
    entries.append('    "BLOCK_REGISTRY",')
    return '__all__ = [\n' + '\n'.join(entries) + '\n]'


def gen_params_module(manifest) -> str:
    """Whole-file content of backend/blocks/_params_gen.py.

    Each parameterized block becomes an `elif node_type == 'xxx':` branch
    that reads the named `data` fields with the manifest's backendParam
    rename (if any) and the backendNeedsSampleRate flag.
    """
    header = (
        '# This file is generated by scripts/codegen-backend.py from blocks.yaml. '
        'Do not edit by hand. See ADR-003.\n'
        '"""Generated parameter mapping.\n\n'
        'Authored by scripts/codegen-backend.py from blocks.yaml. Do not edit\n'
        'by hand; re-run `npm run codegen` after editing the manifest.\n\n'
        'synth.py\'s `_build_params` is a thin wrapper around `build_params`\n'
        'defined here (post-Sprint 21 Phase 1 cutover; see ADR-003).\n'
        '"""\n\n'
        'SAMPLE_RATE = 44100\n\n\n'
        'def build_params(node_type: str, data: dict) -> dict:\n'
        '    params: dict = {}\n'
    )

    # Group blocks by identical parameter-mapping shape so oscillator /
    # triangle / sawtooth / sine collapse to one branch (mirrors synth.py).
    branches = []
    grouped = {}  # signature -> [block types]
    order = []  # preserve manifest order of first occurrence

    for b in manifest:
        if not b.get('parameters'):
            continue
        params = b['parameters']
        # Signature: tuple of (data-field, backend-kwarg, type, needs-SR)
        sig = []
        for key, p in params.items():
            backend_param = p.get('backendParam', key)
            needs_sr = p.get('backendNeedsSampleRate', False)
            sig.append((key, backend_param, p['type'], needs_sr))
        sig_t = tuple(sig)
        if sig_t not in grouped:
            grouped[sig_t] = []
            order.append(sig_t)
        grouped[sig_t].append(b['type'])

    first = True
    for sig_t in order:
        types = grouped[sig_t]
        if len(types) == 1:
            cond = f'node_type == "{types[0]}"'
        else:
            joined = ', '.join(f'"{t}"' for t in types)
            cond = f'node_type in ({joined})'
        keyword = 'if' if first else 'elif'
        first = False
        branch = [f'    {keyword} {cond}:']
        needs_sr_any = False
        for data_key, backend_param, ptype, needs_sr in sig_t:
            if needs_sr:
                needs_sr_any = True
            if ptype == 'int':
                branch.append(f'        if "{data_key}" in data:')
                branch.append(
                    f'            params["{backend_param}"] = int(data["{data_key}"])'
                )
            elif ptype == 'string':
                branch.append(f'        if "{data_key}" in data:')
                branch.append(
                    f'            params["{backend_param}"] = str(data["{data_key}"])'
                )
            elif ptype == 'intArray':
                branch.append(
                    f'        contents = data.get("{data_key}", [])'
                )
                branch.append('        if isinstance(contents, list):')
                branch.append(
                    f'            params["{backend_param}"] = [int(v) for v in contents[:16]]'
                )
                branch.append('        else:')
                branch.append(f'            params["{backend_param}"] = []')
        if needs_sr_any:
            branch.append('        params["sample_rate"] = SAMPLE_RATE')
        branches.append('\n'.join(branch))

    body = '\n'.join(branches) + '\n    return params\n'
    return header + body


# ────────────────────────────────────────────────────────────────────────────
# Anchor-based extractors for --check
# ────────────────────────────────────────────────────────────────────────────


def extract_init_imports(content: str) -> str:
    lines = content.split('\n')
    pat = re.compile(r'^from \.[a-z_][a-z_0-9]* import [A-Za-z]+$')
    start = end = -1
    for i, line in enumerate(lines):
        if pat.match(line):
            if start < 0:
                start = i
            end = i
        elif start >= 0 and end >= 0 and line.strip() == '':
            # Stop at first blank line after the imports run.
            break
    if start < 0:
        return ''
    return '\n'.join(lines[start:end + 1])


def extract_init_registry(content: str) -> str:
    # `# Registry ... BLOCK_REGISTRY = { ... }` block. Use a non-greedy match.
    m = re.search(
        r'(# Registry mapping[^\n]*\n)?BLOCK_REGISTRY = \{[\s\S]*?\n\}',
        content,
    )
    return m.group(0) if m else ''


def extract_init_all(content: str) -> str:
    m = re.search(r'__all__ = \[[\s\S]*?\n\]', content)
    return m.group(0) if m else ''


# ────────────────────────────────────────────────────────────────────────────
# Marker-aware extraction + in-place rewrite
# ────────────────────────────────────────────────────────────────────────────
#
# Marker syntax inside backend Python files:
#   # @begin codegen <slot>
#   ...generated content...
#   # @end codegen <slot>
#
# Phase 1 invariant: after `--write` lands the markers, `--check` reads
# the section between markers; before the cutover, --check falls back to
# the anchor-based extractor so the byte-equality assertion still works
# in the pre-marker world.


def make_markers(slot: str) -> tuple[str, str]:
    return f'# @begin codegen {slot}', f'# @end codegen {slot}'


def extract_by_markers(content: str, slot: str) -> str | None:
    open_marker, close_marker = make_markers(slot)
    pat = re.compile(
        re.escape(open_marker) + r'\n([\s\S]*?)\n[ \t]*' + re.escape(close_marker)
    )
    m = pat.search(content)
    return m.group(1) if m else None


def apply_write(
    content: str,
    slot: str,
    generated: str,
    legacy_extractor,
    target_name: str,
) -> str:
    """Splice `<begin>\\n<generated>\\n<end>` into `content`.

    First run (no markers yet): use `legacy_extractor` to find the live
    section, replace exactly that substring with the marker-bracketed
    generated content.

    Re-run (markers present): swap the body between the existing markers.
    """
    open_marker, close_marker = make_markers(slot)
    re_markers = re.compile(
        '(' + re.escape(open_marker) + r')\n[\s\S]*?\n([ \t]*'
        + re.escape(close_marker) + ')'
    )
    if re_markers.search(content):
        return re_markers.sub(
            lambda m: f'{m.group(1)}\n{generated}\n{m.group(2)}', content,
        )
    live = legacy_extractor(content)
    if not live:
        raise RuntimeError(
            f'cannot locate live section for {target_name}'
        )
    idx = content.find(live)
    if idx < 0:
        raise RuntimeError(
            f'live section text not found for {target_name}'
        )
    replacement = f'{open_marker}\n{live}\n{close_marker}'
    return content[:idx] + replacement + content[idx + len(live):]


# ────────────────────────────────────────────────────────────────────────────
# Diff helper
# ────────────────────────────────────────────────────────────────────────────


def unified_diff(actual: str, expected: str, label: str) -> str:
    a = actual.split('\n')
    b = expected.split('\n')
    out = [f'--- {label} (current)', f'+++ {label} (generated)']
    maxn = max(len(a), len(b))
    in_hunk = False
    for i in range(maxn):
        av = a[i] if i < len(a) else None
        bv = b[i] if i < len(b) else None
        if av != bv:
            if not in_hunk:
                out.append(f'@@ line {i + 1} @@')
                in_hunk = True
            if av is not None:
                out.append('-' + av)
            if bv is not None:
                out.append('+' + bv)
        else:
            in_hunk = False
    return '\n'.join(out)


# ────────────────────────────────────────────────────────────────────────────
# Driver
# ────────────────────────────────────────────────────────────────────────────


def _in_place_targets(manifest):
    """Three __init__.py slot definitions (slot name + extractor + generator)."""
    return [
        {
            'name': '__init__.py:imports',
            'slot': 'block-imports',
            'extractor': extract_init_imports,
            'generator': lambda: gen_init_imports(manifest),
        },
        {
            'name': '__init__.py:BLOCK_REGISTRY',
            'slot': 'block-registry',
            'extractor': extract_init_registry,
            'generator': lambda: gen_init_registry(manifest),
        },
        {
            'name': '__init__.py:__all__',
            'slot': 'block-all',
            'extractor': extract_init_all,
            'generator': lambda: gen_init_all(manifest),
        },
    ]


def _check_section(content: str, target) -> tuple[str, str]:
    """Return (actual, expected) for one __init__.py slot.

    Uses marker-aware extraction first; falls back to the legacy anchor
    extractor so pre-cutover --check still works.
    """
    from_marker = extract_by_markers(content, target['slot'])
    actual = from_marker if from_marker is not None else target['extractor'](content)
    expected = target['generator']()
    return actual, expected


def _run_check(manifest) -> int:
    init_path = REPO_ROOT / 'backend' / 'blocks' / '__init__.py'
    params_path = REPO_ROOT / 'backend' / 'blocks' / '_params_gen.py'

    if not init_path.exists():
        sys.stderr.write(f'[codegen-backend] target missing: {init_path}\n')
        return 2

    init_content = init_path.read_text(encoding='utf-8')

    divergent = 0
    for target in _in_place_targets(manifest):
        actual, expected = _check_section(init_content, target)
        if actual == expected:
            print(f'ok   {target["name"]}')
        else:
            print(f'DIFF {target["name"]}')
            print(unified_diff(actual, expected, target['name']))
            divergent += 1

    # _params_gen.py is whole-file codegen. Compare the generated content
    # against the committed file; skip the assertion if the file does not
    # yet exist (pre-cutover state), still exercising the generator so
    # manifest errors surface.
    if params_path.exists():
        actual = params_path.read_text(encoding='utf-8')
        expected = gen_params_module(manifest)
        if actual == expected:
            print('ok   _params_gen.py (whole file)')
        else:
            print('DIFF _params_gen.py (whole file)')
            print(unified_diff(actual, expected, '_params_gen.py'))
            divergent += 1
    else:
        try:
            gen_params_module(manifest)
            print('skip _params_gen.py (Phase 1 target; file not yet committed)')
        except Exception as exc:  # pragma: no cover — exercised on manifest break
            sys.stderr.write(
                f'[codegen-backend] gen_params_module failed: {exc}\n'
            )
            return 2

    if divergent:
        sys.stderr.write(
            f'\n[codegen-backend] {divergent} target(s) diverged from manifest.\n'
            '  Phase 0 gate: iterate the templates in this script until empty.\n'
        )
        return 1
    print('\n[codegen-backend] all targets match.')
    return 0


def _run_write(manifest) -> int:
    """Phase 1 cutover: insert markers into __init__.py and write _params_gen.py.

    Two-pass: compute every replacement first, then commit to disk. If any
    target fails, abort without touching files — half-written trees were
    the failure mode the Phase 0 brief warned about.
    """
    init_path = REPO_ROOT / 'backend' / 'blocks' / '__init__.py'
    params_path = REPO_ROOT / 'backend' / 'blocks' / '_params_gen.py'

    if not init_path.exists():
        sys.stderr.write(f'[codegen-backend] target missing: {init_path}\n')
        return 2

    init_content = init_path.read_text(encoding='utf-8')
    next_init = init_content
    failed = False
    for target in _in_place_targets(manifest):
        try:
            generated = target['generator']()
            next_init = apply_write(
                next_init,
                target['slot'],
                generated,
                target['extractor'],
                target['name'],
            )
            print(f'write {target["name"]}')
        except Exception as exc:
            sys.stderr.write(f'[codegen-backend] {exc}\n')
            failed = True

    try:
        params_content = gen_params_module(manifest)
        print('write _params_gen.py (whole file)')
    except Exception as exc:
        sys.stderr.write(f'[codegen-backend] gen_params_module failed: {exc}\n')
        failed = True
        params_content = None

    if failed:
        sys.stderr.write('\n[codegen-backend] --write aborted; no files modified.\n')
        return 1

    init_path.write_text(next_init, encoding='utf-8')
    params_path.write_text(params_content, encoding='utf-8')
    print('\n[codegen-backend] all targets written.')
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--write', action='store_true', help='Phase 1 cutover')
    args = parser.parse_args()

    manifest = _load_manifest()

    if args.write:
        return _run_write(manifest)
    return _run_check(manifest)


if __name__ == '__main__':
    sys.exit(main())
