import { type CSSProperties, useMemo, useState } from 'react'
import type { BlockData, BlockPort, DriveKind, PinKind, PinSide } from './blocks.ts'
import { characterizeBlock } from './logic-sim.ts'
import type { Fidelity } from './symbols.tsx'
import { THEME } from './theme.ts'

/**
 * Block pinout editor (Properties panel) — edit a circuit block's external pins like a chip's pinout:
 * NAME each pin, set whether it's a plain signal or a +/− POWER pin (power pins then show +/− in
 * red/blue on the box, the way a real chip marks its supply pins), pick which EDGE it sits on (pins
 * auto-distribute, always centered on that edge), reorder pins within an edge (▲▼), and ADD a pin by
 * exposing any internal terminal — even before it's wired. A pin still IS its internal terminal; this
 * only changes how the block presents to the outside, never the circuit the solver sees.
 */

const field: CSSProperties = {
  background: THEME.surfaceInput,
  border: `1px solid ${THEME.borderStrong}`,
  color: THEME.textPrimary,
  borderRadius: 3,
  padding: '2px 4px',
  fontSize: 11,
}
const arrow: CSSProperties = {
  background: THEME.surfaceInput,
  border: `1px solid ${THEME.borderStrong}`,
  color: THEME.textSoft,
  borderRadius: 3,
  fontSize: 9,
  lineHeight: 1,
  padding: '1px 4px',
  cursor: 'pointer',
}
const remove: CSSProperties = { ...arrow, color: THEME.statusDanger }
const fidelityBtn: CSSProperties = {
  flex: 1,
  background: THEME.surfaceInput,
  border: `1px solid ${THEME.borderStrong}`,
  color: THEME.textSoft,
  borderRadius: 3,
  fontSize: 10,
  padding: '3px 0',
  cursor: 'pointer',
}
const fidelityActive: CSSProperties = {
  ...fidelityBtn,
  background: THEME.accentBlue,
  color: THEME.textBright,
  borderColor: THEME.accentBlue,
}
const SIDE_ORDER: Record<PinSide, number> = { left: 0, right: 1, top: 2, bottom: 3 }

export type BlockPortPatch = {
  name?: string
  kind?: PinKind
  side?: PinSide
  drive?: DriveKind
  enable?: { pin: string; activeHigh: boolean }
}

/** An internal terminal that isn't a pin yet — offered in the "add pin" picker. */
export type AddableTerminal = { nodeId: string; handleId: string; label: string }

export function BlockInspector({
  ports,
  block,
  available,
  fidelity,
  onFidelity,
  onEditPort,
  onAddPort,
  onReorderPort,
  onRemovePort,
  onSaveAsPart,
}: {
  ports: BlockPort[]
  block: BlockData
  available: AddableTerminal[]
  fidelity: Fidelity
  onFidelity: (f: Fidelity) => void
  onEditPort: (portId: string, patch: BlockPortPatch) => void
  onAddPort: (nodeId: string, handleId: string) => void
  onReorderPort: (portId: string, dir: -1 | 1) => void
  onRemovePort: (portId: string) => void
  /** Save this block's circuit as a reusable custom part — returns an error message, or null on success. */
  onSaveAsPart?: (name: string) => string | null
}) {
  // Group the list by edge so the ▲▼ reordering (which moves a pin among its same-side pins) reads
  // naturally; a stable sort keeps each edge's pins in their current order.
  const sorted = [...ports].sort((a, b) => SIDE_ORDER[a.side] - SIDE_ORDER[b.side])
  // The behaviour layer: generate the block's truth table by running its real circuit (memoized per
  // selection — it runs 2^inputs solves). null when it isn't a tableable combinational block.
  const table = useMemo(
    () => (fidelity === 'behaviour' ? characterizeBlock(block) : null),
    [block, fidelity],
  )
  return (
    <div style={{ width: 188, fontSize: 11, color: THEME.textSoft }}>
      <div style={{ fontWeight: 700, color: THEME.textBright, marginBottom: 2 }}>Simulate as</div>
      <div style={{ display: 'flex', gap: 3, marginBottom: 3 }}>
        {(['transistor', 'logic', 'behaviour'] as const).map((f) => (
          <button
            key={f}
            type="button"
            onClick={() => onFidelity(f)}
            style={{ ...(fidelity === f ? fidelityActive : fidelityBtn), fontSize: 9 }}
          >
            {f === 'transistor' ? 'Transistor' : f === 'logic' ? 'Logic' : 'Behaviour'}
          </button>
        ))}
      </div>
      <div style={{ fontSize: 9, color: THEME.textFaint, marginBottom: 8 }}>
        Transistor = the full analog circuit. Logic = fast 0/1 (the gates). Behaviour = the block's
        truth table, generated by running the real circuit. Same circuit inside — descend to see it.
      </div>
      {table ? (
        <div style={{ marginBottom: 8 }}>
          <div style={{ fontWeight: 700, color: THEME.textBright, marginBottom: 2 }}>
            Behaviour — truth table
          </div>
          <div style={{ fontFamily: 'monospace', fontSize: 9, color: THEME.textSoft }}>
            <div style={{ color: THEME.textFaint }}>
              {table.inputs.join(' ')} → {table.outputs.join(' ')}
            </div>
            {table.rows.slice(0, 16).map((r) => (
              <div key={r.in.map((b) => (b ? '1' : '0')).join('')}>
                {r.in.map((b) => (b ? '1' : '0')).join(' ')} →{' '}
                {r.out.map((b) => (b ? '1' : '0')).join(' ')}
              </div>
            ))}
            {table.rows.length > 16 ? (
              <div style={{ color: THEME.textFaint }}>… {table.rows.length} rows total</div>
            ) : null}
          </div>
        </div>
      ) : fidelity === 'behaviour' ? (
        <div style={{ fontSize: 9, color: THEME.textMuted, marginBottom: 8 }}>
          Behaviour needs a combinational block with a few inputs — too many inputs, or stateful
          logic, can't be tabled.
        </div>
      ) : null}
      <div style={{ fontWeight: 700, color: THEME.textBright, marginBottom: 2 }}>
        Pins ({ports.length})
      </div>
      <div style={{ fontSize: 9, color: THEME.textFaint, marginBottom: 6 }}>
        Power pins show +/−; each sits on an edge (auto-spaced). ▲▼ reorders within an edge.
      </div>
      {ports.length === 0 ? (
        <div style={{ fontSize: 10, color: THEME.textMuted }}>
          No pins yet — wire to the block, or add one below.
        </div>
      ) : null}
      {sorted.map((port) => (
        <div
          key={port.id}
          style={{
            borderTop: `1px solid ${THEME.borderSubtle}`,
            paddingTop: 5,
            marginTop: 5,
            display: 'flex',
            flexDirection: 'column',
            gap: 3,
          }}
        >
          <div style={{ display: 'flex', justifyContent: 'space-between', gap: 4 }}>
            <span
              style={{
                fontSize: 9,
                color: THEME.textFaint,
                overflow: 'hidden',
                textOverflow: 'ellipsis',
                whiteSpace: 'nowrap',
              }}
              title={port.label}
            >
              {port.label}
            </span>
            <span style={{ display: 'flex', gap: 2, flexShrink: 0 }}>
              <button
                type="button"
                style={arrow}
                title="Move up on this edge"
                onClick={() => onReorderPort(port.id, -1)}
              >
                ▲
              </button>
              <button
                type="button"
                style={arrow}
                title="Move down on this edge"
                onClick={() => onReorderPort(port.id, 1)}
              >
                ▼
              </button>
              <button
                type="button"
                style={remove}
                title="Remove this pin (deletes any wire attached to it)"
                onClick={() => onRemovePort(port.id)}
              >
                ×
              </button>
            </span>
          </div>
          <input
            value={port.name ?? ''}
            placeholder="pin name (e.g. VCC)"
            onChange={(e) => onEditPort(port.id, { name: e.target.value })}
            style={field}
          />
          <div style={{ display: 'flex', gap: 4 }}>
            <select
              value={port.kind ?? 'signal'}
              onChange={(e) => onEditPort(port.id, { kind: e.target.value as PinKind })}
              style={{ ...field, flex: 1 }}
              title="A power pin shows +/− (red/blue); a signal pin is plain"
            >
              <option value="signal">signal</option>
              <option value="power_positive">+ power</option>
              <option value="power_negative">− power</option>
            </select>
            <select
              value={port.side}
              onChange={(e) => onEditPort(port.id, { side: e.target.value as PinSide })}
              style={{ ...field, flex: 1 }}
              title="Which edge of the block this pin sits on"
            >
              <option value="left">left</option>
              <option value="right">right</option>
              <option value="top">top</option>
              <option value="bottom">bottom</option>
            </select>
          </div>
          <select
            value={port.drive ?? 'input'}
            onChange={(e) => onEditPort(port.id, { drive: e.target.value as DriveKind })}
            style={{ ...field, width: '100%' }}
            title="Signal direction / drive type — the basis of the output-combining (driver-contention) checks"
          >
            <option value="input">input</option>
            <option value="push_pull">output: push-pull (normal)</option>
            <option value="open_collector">output: open-collector / drain</option>
            <option value="tristate">output: tri-state</option>
          </select>
          {port.drive === 'tristate' ? (
            <div style={{ display: 'flex', gap: 4 }}>
              <select
                value={port.enable?.pin ?? ''}
                onChange={(e) =>
                  onEditPort(port.id, {
                    enable: { pin: e.target.value, activeHigh: port.enable?.activeHigh ?? true },
                  })
                }
                style={{ ...field, flex: 1 }}
                title="Which pin enables this tri-state output — lets the live check count how many drive the bus at once"
              >
                <option value="">(no enable set)</option>
                {ports
                  .filter((p) => p.id !== port.id)
                  .map((p) => (
                    <option key={p.id} value={p.id}>
                      en: {p.name ?? p.label}
                    </option>
                  ))}
              </select>
              <select
                value={port.enable?.activeHigh === false ? 'low' : 'high'}
                onChange={(e) => {
                  if (port.enable) {
                    onEditPort(port.id, {
                      enable: { pin: port.enable.pin, activeHigh: e.target.value === 'high' },
                    })
                  }
                }}
                disabled={port.enable === undefined}
                style={{ ...field, width: 64 }}
                title="Is the output enabled when the enable pin is HIGH or LOW?"
              >
                <option value="high">on=hi</option>
                <option value="low">on=lo</option>
              </select>
            </div>
          ) : null}
        </div>
      ))}
      {available.length > 0 ? (
        <select
          value=""
          onChange={(e) => {
            const sep = e.target.value.indexOf('::')
            if (sep < 0) return
            onAddPort(e.target.value.slice(0, sep), e.target.value.slice(sep + 2))
          }}
          style={{ ...field, marginTop: 8, width: '100%' }}
          title="Expose an internal terminal as a pin — even before you wire to it"
        >
          <option value="">+ Add pin (expose a terminal)…</option>
          {available.map((t) => (
            <option key={`${t.nodeId}::${t.handleId}`} value={`${t.nodeId}::${t.handleId}`}>
              {t.label}
            </option>
          ))}
        </select>
      ) : null}
      {onSaveAsPart ? <SaveAsPart onSave={onSaveAsPart} /> : null}
    </div>
  )
}

/**
 * "Save as custom part" (user-made parts, slice 4b Model B): turn THIS block's real internal circuit
 * into a reusable custom part — its pins are the block's pins, its physics is the circuit inside. The
 * part joins the palette and your personal library like any authored part.
 */
function SaveAsPart({ onSave }: { onSave: (name: string) => string | null }) {
  const [name, setName] = useState('')
  const [status, setStatus] = useState<{ ok: boolean; text: string } | null>(null)
  return (
    <div style={{ borderTop: `1px solid ${THEME.borderSubtle}`, paddingTop: 8, marginTop: 10 }}>
      <div style={{ fontWeight: 700, color: THEME.textBright, marginBottom: 2 }}>
        Save as custom part
      </div>
      <div style={{ fontSize: 9, color: THEME.textFaint, marginBottom: 4 }}>
        Makes this block a reusable part: same pins, and it simulates as the real circuit inside.
        Saved to your parts library.
      </div>
      <div style={{ display: 'flex', gap: 4 }}>
        <input
          value={name}
          placeholder="part name (e.g. My Amp)"
          onChange={(e) => {
            setName(e.target.value)
            setStatus(null)
          }}
          style={{ ...field, flex: 1 }}
        />
        <button
          type="button"
          onClick={() => {
            const error = onSave(name)
            if (error !== null) {
              setStatus({ ok: false, text: error })
              return
            }
            setStatus({ ok: true, text: 'Saved — it’s in the palette under “Your parts”.' })
            setName('')
          }}
          style={{ ...arrow, fontSize: 10, padding: '3px 8px' }}
        >
          Save
        </button>
      </div>
      {status ? (
        <div
          style={{
            fontSize: 9,
            marginTop: 3,
            color: status.ok ? THEME.statusOk : THEME.statusDanger,
          }}
        >
          {status.text}
        </div>
      ) : null}
    </div>
  )
}
