/**
 * The Board manufacturing-readiness PLAN — the tiered work to make ChipBlocks' PCB rules match real fab
 * constraints, tracked in the Plan dock so nothing is lost. Every value is the RECONFIRMED number (fact-
 * checked against JLCPCB/PCBWay/IPC in a verification workflow, 2026-07-19), cited on the item. DECLARATIVE:
 * edit this one list to change the plan; the Plan panel renders it. `status` is the authored state (updated
 * as each item ships); a user can also toggle status in the panel (stored per-id in localStorage).
 */

export type PlanItemSize = 'S' | 'M' | 'L'
export type PlanStatus = 'todo' | 'doing' | 'done'
export type PlanItem = {
  id: string
  title: string
  /** What the change is, in one line. */
  what: string
  /** The real-world number(s) this item must honour. */
  value: string
  /** Where the number comes from (fab capability page / IPC standard / code location). */
  cite: string
  /** Rough effort. */
  size: PlanItemSize
  /** Authored/default status; per-id user overrides live in localStorage. */
  status: PlanStatus
  /** The source area this touches (for the builder). */
  code?: string
}
export type PlanTier = { tier: number; name: string; items: PlanItem[] }

export const BOARD_PLAN: PlanTier[] = [
  {
    tier: 0,
    name: 'Honesty & correctness patches (small, high-value, no new canvas objects)',
    items: [
      {
        id: 'trace-width-by-copper-weight',
        title: 'Trace/space min scales with copper weight',
        what: "Replace the flat 0.2mm track-width DRC (cited to KiCad's editor default) with a copper-weight table; wire runDrc's existing copperWeight option into the track-width and spacing checks, not just over-current.",
        value:
          '1oz cap 0.10mm/design 0.127-0.15mm; 2oz 0.15-0.16mm; 2.5oz 0.20mm; 3.5oz 0.25mm; 4.5oz 0.30mm.',
        cite: 'https://jlcpcb.com/capabilities/pcb-capabilities',
        size: 'M',
        status: 'done',
        code: 'src/renderer/pcb-drc.ts:141-151,296-306,461-538',
      },
      {
        id: 'annular-ring-drc',
        title: 'Annular-ring DRC at 0.15mm (not 0.05mm)',
        what: 'Add a min-annular-ring rule = (pad_dia − drill_dia)/2 ≥ 0.15mm for PTH/via; keep 0.05mm only as the smallest-via geometric floor, not the rule. NPTH pad ring ≥0.45mm.',
        value: '0.15mm (6mil) ring, recommended 0.20mm; NPTH ≥0.45mm pad.',
        cite: 'https://jlcpcb.com/capabilities/pcb-capabilities',
        size: 'S',
        status: 'done',
        code: 'src/renderer/pcb-drc.ts (new rule)',
      },
      {
        id: 'min-drill-aspect-ratio',
        title: 'Min drill = max(0.15mm, thickness/8)',
        what: 'Make min drill thickness-dependent via 8:1 aspect ratio instead of a flat 0.3mm; recommended floor 0.2mm, hard 0.15mm; drill steps 0.05mm.',
        value: 'Hard 0.15mm, recommended 0.2mm, aspect 8:1 std (10:1 adv).',
        cite: 'https://jlcpcb.com/capabilities/pcb-capabilities ; IPC-2221B/6012',
        size: 'M',
        status: 'done',
        code: 'src/renderer/pcb-drc.ts',
      },
      {
        id: 'max-drill-route',
        title: 'Max drill 6.30mm → must be a slot',
        what: 'Flag round holes >6.30mm (and elongated holes) as route-layer slots, not drills.',
        value: 'Circular drill 0.15-6.30mm; larger = milled slot.',
        cite: 'https://jlcpcb.com/capabilities/pcb-capabilities',
        size: 'S',
        status: 'done',
        code: 'src/renderer/pcb-drc.ts / pcb-gerber.ts drill',
      },
      {
        id: 'npth-split-drill-file',
        title: 'NPTH holes in a separate non-plated drill file',
        what: 'Add a plated flag to Pad/hole; mounting/tooling holes default NPTH; emit a second Excellon file (FileFunction NonPlated) alongside the PTH file. Grounded mounting holes stay PTH by choice.',
        value:
          'KiCad default: separate PTH + NPTH Excellon files; mounting holes NPTH by DFM default.',
        cite: 'rheingoldheavy.com/combining-kicad-drill-files; digikey forum',
        size: 'M',
        status: 'done',
        code: 'src/renderer/pcb-gerber.ts:534-593; pcb-fab.ts:507',
      },
      {
        id: 'silk-stroke-and-height-drc',
        title: 'Silk min-stroke 0.15mm + min char height 1.0mm DRC',
        what: 'Add a silk-stroke-width DRC (new DrcCode) and a min-char-height check; bump shipped 0.12mm silk strokes to ≥0.15mm. Distinguish F.SilkS (printed) from F.Fab (not manufactured).',
        value:
          'Stroke ≥0.15mm (6mil), char height ≥1.0mm (40mil); 0.10mm/0.8mm high-precision only.',
        cite: 'https://jlcpcb.com/capabilities/pcb-capabilities',
        size: 'M',
        status: 'done',
        code: 'src/renderer/pcb-drc.ts:38-50,401-455; footprint.ts:379,403,948,1014; stroke-font.ts:21',
      },
      {
        id: 'silk-to-pad-clearance-fix',
        title: 'Positive silk-to-pad clearance (~0.15mm)',
        what: 'Change the silk-over-pad check from distance-0 overlap to a positive 0.15mm gap to the mask opening.',
        value: '~0.15mm (6mil) silk-to-pad.',
        cite: 'JLCPCB / OSH Park silk-to-pad ~0.15mm',
        size: 'S',
        status: 'done',
        code: 'src/renderer/pcb-drc.ts:420-444',
      },
      {
        id: 'board-size-limits',
        title: 'Min/max board-size checks',
        what: 'Flag boards below 3x3mm (warn <5x5mm practical) and above the layer-count-dependent max; note V-cut panels need ≥70x70mm.',
        value:
          'Min 3x3mm hard / 5x5mm practical; max 400x500mm cheap → 656x586mm 6-layer, extended 2L 1020x600mm.',
        cite: 'https://jlcpcb.com/capabilities/pcb-capabilities',
        size: 'S',
        status: 'done',
        code: 'src/renderer/pcb-drc.ts / pcb-board.ts',
      },
      {
        id: 'v-cut-edge-clearance-0.4',
        title: 'V-cut copper-to-edge 0.4mm (distinct from 0.3mm routed)',
        what: 'Add a per-edge V-cut clearance value (0.4mm) separate from the single flat 0.3mm routed-edge rule. (Full V-groove rules deferred to Tier 4.)',
        value: '≥0.4mm copper-to-edge along a V-scored line.',
        cite: 'https://jlcpcb.com/capabilities/pcb-capabilities',
        size: 'S',
        status: 'done',
        code: 'src/renderer/pcb-drc.ts:129-140,278-293',
      },
      {
        id: 'castellated-min-0.6',
        title: 'Castellated half-hole ≥0.6mm design min',
        what: 'Add castellated-hole rule: ≥0.6mm diameter (0.5mm bare floor), ≥0.6mm edge-to-edge, ~0.25mm ring.',
        value: '0.6mm design min / 0.5mm capability floor.',
        cite: 'jlcpcb.com/blog/castellated-pcbs-introduction-and-design-requirements',
        size: 'S',
        status: 'done',
        code: 'src/renderer/pcb-drc.ts',
      },
      {
        id: 'voltage-clearance-creepage-t0',
        title: 'Voltage-based clearance/creepage check',
        what: 'Compute per-net-pair spacing from the solved peak ΔV; compare against IPC-2221B Table 6-1 (and creepage via CTI); report which rule governs. Prevents silently passing a board that arcs above ~30V.',
        value:
          '~0.6mm at 50-150V, ~2.5mm at 500V, 0.005mm/V >500V (external uncoated); creepage per CTI/pollution degree.',
        cite: 'IPC-2221B Table 6-1; IEC 60664-1; IEC 60112',
        size: 'L',
        status: 'done',
        code: 'src/renderer/pcb-drc.ts (new voltage-aware spacing pass)',
      },
      {
        id: 'ir-drop-t0',
        title: 'DC IR-drop budget on power/ground nets',
        what: "Sum I·R along each rail's delivery path; compare against rail tolerance; distinct from the existing thermal ampacity check.",
        value: 'e.g. 1.0V ±3% rail tolerates ~30mV total drop; R = ρL/(w·t).',
        cite: 'IPC-2152 copper resistance + rail budgeting',
        size: 'M',
        status: 'done',
        code: 'src/renderer/pcb-drc.ts:917',
      },
      {
        id: 'thermal-via-false-reject-t0',
        title: 'Stop false-rejecting same-net thermal-via arrays',
        what: "Add a thermal-pad concept; exempt same-net vias inside a thermal pad from the via-in-pad DRC so a legitimate thermal-via array isn't flagged as a defect.",
        value: '~0.3mm vias at ~1.0-1.2mm pitch, filled-and-capped (IPC-4761 type IV/Vb-VII).',
        cite: 'IPC-7093; IPC-4761; JLCPCB thermal-pad guidance',
        size: 'M',
        status: 'done',
        code: 'src/renderer/pcb-drc.ts:331-347',
      },
      {
        id: 'component-edge-keepout-t0',
        title: 'Component-to-edge assembly keepout',
        what: 'Flag part bodies within ~3-5mm of the board edge (the auto-fit outline currently guarantees this violation). Interim check now; full rail object in Tier 4.',
        value:
          '3-5mm part-free rail keepout on ≥2 edges (distinct from 0.3mm copper edge-clearance).',
        cite: 'IPC-2221 board-edge clearance; SMT DFM',
        size: 'M',
        status: 'done',
        code: 'src/renderer/pcb-board.ts:170-175; pcb-drc.ts',
      },
    ],
  },
  {
    tier: 1,
    name: 'Custom board shape on the canvas (user-authored outline)',
    items: [
      {
        id: 'user-outline',
        title: 'User-settable, persisted board outline (arcs + cutouts)',
        what: 'Replace the auto-fit rectangle {x,y,w,h} with a user-drawn, saved Edge.Cuts polygon/arc outline + internal cutouts; export real geometry, not 4 straight lines.',
        value: 'Non-rectangular outlines, internal cutouts, arcs.',
        cite: 'KiCad Edge.Cuts; IPC-2221 outline. Code: pcb-board.ts:33-34,113,147,170-175; pcb-gerber.ts:485-522',
        size: 'L',
        status: 'todo',
        code: 'src/renderer/pcb-board.ts; pcb-gerber.ts',
      },
      {
        id: 'internal-corner-radius-t1',
        title: 'Min internal corner radius = router-bit radius',
        what: 'On any concave corner of the outline/cutout, enforce a bit-radius fillet (~0.8mm, ~0.5mm small bit); flag sharp inside corners as uncuttable.',
        value: '~0.8mm (1.6mm bit) / ~0.5mm small bit.',
        cite: 'Fab mechanical routing; IPC-2221',
        size: 'M',
        status: 'todo',
        code: 'src/renderer/pcb-board.ts; pcb-drc.ts',
      },
      {
        id: 'internal-slots-t1',
        title: 'Internal slots / cutouts object',
        what: 'Add a routed-slot object (connector cutouts, mounting slots) on the route layer with min width; slot-vs-drill threshold.',
        value: 'Routed slot min ~1.0mm; <0.6mm drilled/laser; length>diameter or dia>6.3mm = slot.',
        cite: 'JLCPCB slot spec; IPC-2221',
        size: 'M',
        status: 'todo',
        code: 'src/renderer/pcb-board.ts; pcb-gerber.ts',
      },
      {
        id: 'outline-tolerance-t1',
        title: 'Routed-outline mechanical tolerance band',
        what: 'Attach a ±0.1-0.2mm tolerance to the finished outline/slot positions for enclosure-fit reasoning.',
        value: '±0.13mm typical (±0.1-0.2mm).',
        cite: 'IPC-2221/6012 dimensional tolerancing',
        size: 'S',
        status: 'todo',
        code: 'src/renderer/pcb-board.ts',
      },
    ],
  },
  {
    tier: 2,
    name: 'Copper pour / ground planes (unlocks return-path, plane ampacity, warp)',
    items: [
      {
        id: 'copper-pour-object',
        title: 'Copper-pour / filled-zone / plane object',
        what: 'Add a poured-copper region type (thermal reliefs, anti-pads, keepouts) to Board/BoardRouting; emit real copper-fill Gerber regions. Today copper is only traces + via barrels + pad flashes.',
        value:
          'Filled ground/power zones, needed by the impedance math which already assumes a solid reference plane.',
        cite: 'Code: pcb-board.ts:53; pcb-route.ts:155-158; pcb-gerber.ts:324-393 (no fill emitted)',
        size: 'L',
        status: 'todo',
        code: 'src/renderer/pcb-board.ts; pcb-route.ts; pcb-gerber.ts',
      },
      {
        id: 'return-path-drc',
        title: 'Return-path / reference-plane continuity DRC',
        what: 'Verify every controlled-Z / high-edge-rate net has a solid adjacent reference plane over its length; flag plane-split crossings and reference changes without a nearby stitching via.',
        value: 'Return current follows the trace; a split crossing = discontinuity + EMI.',
        cite: 'IPC-2251; Johnson & Graham',
        size: 'L',
        status: 'todo',
        code: 'src/renderer/pcb-drc.ts (needs pour object)',
      },
      {
        id: 'plane-current-density-t2',
        title: 'Plane current density / necking (IPC-2152)',
        what: 'Per-region current-density check on plane copper around anti-pads, via fields, slots; cite IPC-2152 as the modern ampacity basis.',
        value: 'Local crowding can exceed ampacity while the average looks fine.',
        cite: 'IPC-2152',
        size: 'M',
        status: 'todo',
        code: 'src/renderer/pcb-fab.ts:317',
      },
      {
        id: 'diff-pairs-t2',
        title: 'Differential-pair impedance + skew + length matching',
        what: 'Add Zdiff, intra-pair skew, inter-pair/bus length matching, uniform coupling to the stackup module.',
        value: 'USB2 90Ω, Ethernet/LVDS 100Ω, PCIe/SATA/HDMI 85-100Ω ±10%; skew ≤~0.13mm USB2.',
        cite: 'USB 2.0; IEEE 802.3; PCIe base. Code: pcb-stackup.ts:565-687',
        size: 'L',
        status: 'todo',
        code: 'src/renderer/pcb-stackup.ts',
      },
      {
        id: 'impedance-tolerance-t2',
        title: 'Controlled-impedance tolerance band (±10%)',
        what: 'Express Z0/Zdiff as a ±10% target band, not an exact number.',
        value: '±10% typical.',
        cite: 'IPC-2141A / fab tolerance',
        size: 'S',
        status: 'todo',
        code: 'src/renderer/pcb-stackup.ts:565-687',
      },
      {
        id: 'teardrops-t2',
        title: 'Teardrops at pad/via junctions',
        what: 'Add teardrop geometry where trace width < pad/via dia (mechanical + electrical).',
        value: 'Recommended where trace < pad/via diameter.',
        cite: 'IPC-7351 / fab DFM',
        size: 'M',
        status: 'todo',
        code: 'src/renderer/pcb-route.ts',
      },
      {
        id: 'parallel-thermal-vias-t2',
        title: 'Parallel-via / thermal-via-array recommendation',
        what: 'On a high-current net, recommend N parallel vias; model thermal-via arrays under power/thermal pads; plane-necking check at via fields.',
        value: 'Split current across N barrels; array to move heat to inner/bottom copper.',
        cite: 'IPC-2152. Code: pcb-fab.ts:321',
        size: 'M',
        status: 'todo',
        code: 'src/renderer/pcb-fab.ts:321',
      },
      {
        id: 'copper-balance-warp-t2',
        title: 'Copper balance / bow-and-twist warp risk',
        what: 'Once pour exists, measure copper distribution and flag layouts likely to exceed 0.75% (0.5% for BGA/fine-pitch) bow-and-twist.',
        value: '≤0.75% general, ≤0.5% BGA/fine-pitch, per IPC-6012 / IPC-TM-650 2.4.22.',
        cite: 'IPC-6012 / IPC-A-600; IPC-2221 copper balance',
        size: 'M',
        status: 'todo',
        code: 'src/renderer/pcb-drc.ts (needs pour object)',
      },
    ],
  },
  {
    tier: 3,
    name: 'Assembly features (ride with footprints / placement)',
    items: [
      {
        id: 'fiducials-t3',
        title: 'Fiducials (global + local pairs)',
        what: 'Add fiducial objects: ≥3 non-collinear global (asymmetric) per board; local pairs diagonally across fine-pitch/BGA. Distinguish 1.0mm copper dot, 2.0mm mask opening, and ~3mm copper-free keepout.',
        value: '1.0mm dot, 2.0mm mask, ~3mm keepout; 3 global asymmetric (2 = bare min).',
        cite: 'pcbsync.com/fiducial-pcb; IPC-7351; IPC-A-610',
        size: 'M',
        status: 'todo',
        code: 'src/renderer/footprint.ts; pcb-board.ts',
      },
      {
        id: 'paste-area-ratio-t3',
        title: 'Paste stencil area-ratio check (IPC-7525)',
        what: 'For each paste aperture compute area ratio = (L·W)/[2(L+W)T]; flag <0.66 (target ≥0.75); companion aspect ratio W/T ≥1.5.',
        value: '≥0.66 min, ≥0.75 production; aspect ≥1.5.',
        cite: 'IPC-7525A; pcbcart area-ratio article',
        size: 'M',
        status: 'todo',
        code: 'src/renderer/footprint.ts (paste layer) + new DRC',
      },
      {
        id: 'soldermask-sliver-t3',
        title: 'Solder-mask sliver/dam minimum',
        what: 'Flag mask dams below the color-dependent minimum; note the flake-off threshold.',
        value:
          'Green ≥0.1mm (4mil), non-green ≥0.125mm (5mil); floating slivers <0.075mm flake off.',
        cite: 'resources.pcb.cadence.com; aptpcb.com solder-mask rules',
        size: 'M',
        status: 'todo',
        code: 'src/renderer/pcb-drc.ts (mask layer)',
      },
      {
        id: 'thermal-relief-t3',
        title: 'Thermal-relief spokes (thermal + electrical)',
        what: 'Model 4-spoke reliefs (3 acceptable) on plane connections; sum-of-spoke-widths = required trace width; flag reliefs (added R) on high-current pins that should be solid.',
        value: '4 spokes std, 0.2-0.5mm width, sum = trace width.',
        cite: 'IPC-7251 / IPC-7351; atlaspcb thermal-relief',
        size: 'M',
        status: 'todo',
        code: 'src/renderer/pcb-route.ts (needs pour); pcb-drc.ts',
      },
      {
        id: 'designator-uniqueness-t3',
        title: 'Reference-designator uniqueness/presence/legibility',
        what: 'Check every part has a unique, present, non-hidden designator; height ≥1.0mm necessary but not sufficient.',
        value: 'No duplicate/missing/obscured designators.',
        cite: 'IPC-2221 / IPC-7351 assembly documentation',
        size: 'S',
        status: 'todo',
        code: 'src/renderer/pcb-drc.ts',
      },
      {
        id: 'smd-nsmd-t3',
        title: 'SMD vs NSMD pad definition',
        what: 'Add a per-pad SMD/NSMD choice; BGA/CSP default NSMD (~60-75µm/side), thermal/large pads SMD.',
        value: 'NSMD mask ~60-75µm larger than copper per side.',
        cite: 'IPC-7351 / IPC-A-610; JEDEC BGA',
        size: 'M',
        status: 'todo',
        code: 'src/renderer/footprint.ts; pcb-gerber.ts mask',
      },
      {
        id: 'tombstone-symmetry-t3',
        title: 'Chip-passive thermal symmetry (tombstoning)',
        what: 'Check both pads of a two-terminal chip have equal thermal mass: symmetric trace entry, equal relief, no heat-robbing via/plane on one end.',
        value: 'Symmetric entry; worst at ≤0402.',
        cite: 'IPC-7351 / IPC-A-610; IPC-7525',
        size: 'M',
        status: 'todo',
        code: 'src/renderer/pcb-drc.ts',
      },
      {
        id: 'z-height-keepout-t3',
        title: 'Component-height / z-axis keepout',
        what: 'Add height zones + shield/heatsink/enclosure clearance; feed the existing pcb-3d.ts model into DRC (courtyard is XY-only).',
        value: 'Max-height zones; connector mating envelopes.',
        cite: 'IPC-7351B (courtyard XY only). Code: pcb-3d.ts exists, DRC ignores z',
        size: 'M',
        status: 'todo',
        code: 'src/renderer/pcb-drc.ts; pcb-3d.ts',
      },
      {
        id: 'decoupling-pdn-t3',
        title: 'Decoupling-cap placement + PDN loop inductance',
        what: 'Check decap-to-pin proximity, mounting loop-inductance estimate, and target-impedance coverage.',
        value: 'Zmax = ΔV_ripple / ΔI_transient; bulk+HF mix.',
        cite: 'IPC-2251 / PDN target-impedance; Novak',
        size: 'M',
        status: 'todo',
        code: 'src/renderer/pcb-drc.ts',
      },
      {
        id: 'crosstalk-3w-t3',
        title: 'Crosstalk / 3W adjacent-trace spacing',
        what: 'Flag parallel signal traces closer than ~2x width edge-to-edge (3W center-to-center); 5W/guard for clocks.',
        value: 'Edge-to-edge ≥2x width for ~1% crosstalk.',
        cite: 'IPC-2251; Johnson & Graham 3W',
        size: 'M',
        status: 'todo',
        code: 'src/renderer/pcb-drc.ts',
      },
      {
        id: 'acid-traps-copper-balance-t3',
        title: 'Acute-angle acid traps + copper thieving',
        what: 'Flag conductor angles <90° (acid traps); add thieving copper to balance distribution.',
        value: 'Angles ≥90°; balanced copper.',
        cite: 'PCB fab DFM (acid-trap; copper balancing)',
        size: 'S',
        status: 'todo',
        code: 'src/renderer/pcb-drc.ts',
      },
    ],
  },
  {
    tier: 4,
    name: 'Defer — panelization, V-score detail, HDI, specialized connectors, 2.5-D',
    items: [
      {
        id: 'breakaway-rails-t4',
        title: 'Breakaway rails / tooling strips',
        what: 'Rail object (~5mm) carrying global fiducials + tooling holes; conveyor-clamp keepout ~3-5mm; removed after assembly.',
        value: '~5mm rails, ~3-5mm keepout.',
        cite: 'IPC-7351 / IPC-A-610; SMT handling',
        size: 'L',
        status: 'todo',
        code: 'panelization (new module)',
      },
      {
        id: 'mouse-bites-t4',
        title: 'Mouse-bite / breakaway-tab panelization',
        what: 'Tab object with drill perforations; support every ~75mm + corners; residual-nib keepout.',
        value: '~4-5 × 0.5mm drills, ~1mm pitch, ~2-3mm tab; support ~75mm.',
        cite: 'IPC-2221 panelization',
        size: 'L',
        status: 'todo',
        code: 'panelization (new module)',
      },
      {
        id: 'v-groove-full-t4',
        title: 'V-groove full rules (web, angle, thickness, straight-only)',
        what: 'Model residual web ~1/3 thickness, 30/45/60° angle, ≤~2.4mm thickness, straight-line-only, cutter keepout. (0.4mm edge clearance already done in Tier 0.)',
        value: 'Web ~0.4mm on 1.6mm; 30/45/60°; ≤2.4mm; straight only.',
        cite: 'IPC-2221; JLCPCB/PCBWay V-cut',
        size: 'M',
        status: 'todo',
        code: 'panelization (new module)',
      },
      {
        id: 'panel-web-gap-t4',
        title: 'Min web/gap between boards in a routed panel',
        what: 'Enforce ~1.6-2.0mm routed gap; V-cut boards abut ~0mm.',
        value: '~1.6-2.0mm routed (2mm bit).',
        cite: 'Fab panelization spec',
        size: 'S',
        status: 'todo',
        code: 'panelization (new module)',
      },
      {
        id: 'panel-global-fiducials-xout-t4',
        title: 'Panel global fiducials + X-out marking',
        what: '3 non-collinear global fiducials on rails + bad-board X-out convention.',
        value: '3 × 1mm dots (2mm mask) on rails; X-out defective boards.',
        cite: 'IPC-7351B; IPC-A-610 X-out',
        size: 'S',
        status: 'todo',
        code: 'panelization (new module)',
      },
      {
        id: 'edge-plating-t4',
        title: 'Continuous edge (wrap) plating',
        what: 'Copper-to-outline + plating step on routed edges; incompatible with V-scoring there.',
        value: 'EMI shield / edge ground / edge soldering.',
        cite: 'IPC-A-600 / fab edge-plating',
        size: 'M',
        status: 'todo',
        code: 'pcb-board.ts; pcb-gerber.ts',
      },
      {
        id: 'gold-fingers-t4',
        title: 'Card-edge gold fingers (bevel + hard gold + keepout)',
        what: 'Edge-connector object: mask/copper pullback, hard gold, 20/30/45° bevel, connector-standard pitch/length.',
        value: 'Hard Au ~30-50µin/Ni; 20° bevel (PCIe CEM).',
        cite: 'IPC-A-600; PCIe CEM; IPC-4552',
        size: 'M',
        status: 'todo',
        code: 'footprint.ts; pcb-board.ts',
      },
      {
        id: 'countersink-counterbore-t4',
        title: 'Countersink / counterbore hole profiles',
        what: 'Depth-controlled conical/flat-bottom hole types beyond straight barrels.',
        value: 'Countersink 82°/90°; counterbore pocket.',
        cite: 'ANSI/ISO fastener angles; fab controlled-depth',
        size: 'M',
        status: 'todo',
        code: 'pcb-board.ts hole model',
      },
      {
        id: 'controlled-depth-backdrill-t4',
        title: 'Controlled-depth routing / cavities / back-drilling',
        what: '2.5-D Z features: depth-milled pockets, back-drilled via stubs, with depth tolerance.',
        value: 'Depth ±0.1-0.15mm.',
        cite: 'IPC-2226 / IPC-6012 back-drill',
        size: 'L',
        status: 'todo',
        code: 'pcb-board.ts (new Z model)',
      },
      {
        id: 'insertion-loss-t4',
        title: 'High-speed insertion loss + via stubs',
        what: 'Surface dB/inch loss budget (skin effect √f + tanδ) and low-Dk/Df laminate choice; flag long via stubs (back-drill).',
        value: 'Loss-tangent + skin-effect length budget.',
        cite: 'IPC-2141A (static Z0 only); SI theory',
        size: 'M',
        status: 'todo',
        code: 'pcb-stackup.ts',
      },
      {
        id: 'fusing-current-t4',
        title: 'Trace fusing (fault-withstand) current',
        what: "Check power/fault traces against Onderdonk fusing for the protection device's clearing time.",
        value: 'Onderdonk/Preece; distinct from steady ampacity.',
        cite: 'Onderdonk equation; Preece',
        size: 'S',
        status: 'todo',
        code: 'pcb-fab.ts',
      },
      {
        id: 'via-stitching-fencing-t4',
        title: 'Via stitching / ground-via fencing',
        what: 'Stitching vias at reference changes; guard-via fences at edges/RF, ≤λ/20.',
        value: 'Fence spacing ≤ λ/20.',
        cite: 'EMC practice; IPC-2251',
        size: 'M',
        status: 'todo',
        code: 'pcb-drc.ts (needs pour)',
      },
      {
        id: 'wave-solder-orientation-t4',
        title: 'Wave-solder shadowing / orientation (THT)',
        what: 'Orientation-for-wave model: long axis parallel to travel, no shadowing, trailing-edge thieving.',
        value: 'Parallel-to-travel; anti-shadow.',
        cite: 'IPC-A-610 / IPC-2221 wave-solder DFM',
        size: 'S',
        status: 'todo',
        code: 'pcb-drc.ts',
      },
      {
        id: 'courtyard-density-t4',
        title: 'Courtyard density levels (rework access)',
        what: 'Offer IPC-7351 Most/Nominal/Least density; warn when tightest under-provides rework/iron access.',
        value: 'Level A/B/C spacing.',
        cite: 'IPC-7351B density levels',
        size: 'S',
        status: 'todo',
        code: 'footprint.ts courtyard',
      },
    ],
  },
]
