/**
 * VERILOG BRIDGE (export half) — a design's gates written out as real Verilog. Verilog here is a
 * REPRESENTATION + interchange format (the same role SPICE and KiCad already play on the CircuitFile
 * hub), NOT a second thing that simulates: the real gate blocks stay the source of truth; this only
 * DESCRIBES them. This is the EXPORT side of the structural bridge (gates → gate-level Verilog); the
 * later synthesizer's OUTPUT is exactly this format, so building it first de-risks that work.
 *
 * It emits IEEE 1364-2005-conformant STRUCTURAL Verilog: a module whose body is the language's built-in
 * gate PRIMITIVES (and / or / not / nand / nor / xor / xnor / buf, output-first), wired by nets — the
 * 1:1 image of ChipBlocks' gate blocks. Verilog gate primitives are POWERLESS (no supply pins), so the
 * physical VDD/GND rails are dropped here and re-synthesized on import; the module interface is the
 * design's SIGNAL ports only. Net and instance names are freshly generated LEGAL identifiers (the raw
 * internal net ids contain characters Verilog forbids), mirroring how serializeSpiceNetlist names nets.
 *
 * Built from scratch — no HDL toolchain is bundled (a choice for the project's own-engine identity, not
 * for licensing). ATTRIBUTION: the language is IEEE Std 1364 (Verilog HDL); the structural subset +
 * primitive syntax were cross-checked against Icarus Verilog, Verilator, and Yosys — no code from any is
 * used or bundled (their individual licenses are recorded in CREDITS.md).
 */

import {
  type BlockData,
  type BlockPort,
  type CanvasEdgeLike,
  type CanvasNodeLike,
  flattenBlocks,
} from './blocks.ts'
import { isLogicGate, isOutputPort, POWER_PORT_IDS } from './logic-sim.ts'
import { buildNets, endpointKey } from './output-contention.ts'

/** ChipBlocks gate block `name` → the Verilog built-in primitive keyword (a 1:1 map). */
const PRIMITIVE_OF: Record<string, string> = {
  NOT: 'not',
  Buffer: 'buf',
  AND: 'and',
  OR: 'or',
  NAND: 'nand',
  NOR: 'nor',
  XOR: 'xor',
  XNOR: 'xnor',
}

/** Verilog-2005 keywords a generated identifier must not collide with (includes the gate primitives, so a
 *  net can never be named `and`). Not exhaustive of the whole language — just what our emitter can produce. */
const RESERVED = new Set([
  'module',
  'endmodule',
  'input',
  'output',
  'inout',
  'wire',
  'reg',
  'supply0',
  'supply1',
  'assign',
  'always',
  'initial',
  'begin',
  'end',
  'if',
  'else',
  'case',
  'endcase',
  'posedge',
  'negedge',
  'parameter',
  'localparam',
  'integer',
  'genvar',
  'generate',
  'endgenerate',
  'and',
  'or',
  'not',
  'nand',
  'nor',
  'xor',
  'xnor',
  'buf',
  'bufif0',
  'bufif1',
  'notif0',
  'notif1',
])

/** Turn an arbitrary name into a legal, unique Verilog identifier: keep [A-Za-z0-9_$], make it start with
 *  a letter/underscore, dodge reserved words, and disambiguate against names already used. */
function sanitizeIdent(raw: string, used: Set<string>): string {
  let base = raw.replace(/[^A-Za-z0-9_$]/g, '_')
  if (base === '' || !/^[A-Za-z_]/.test(base)) base = `n_${base}`
  if (RESERVED.has(base)) base = `${base}_`
  let name = base
  let i = 1
  while (used.has(name)) {
    name = `${base}_${i}`
    i += 1
  }
  used.add(name)
  return name
}

/** A fresh unique name with the given prefix (w1, w2, …). */
function freshName(prefix: string, used: Set<string>): string {
  let i = 1
  let name = `${prefix}${i}`
  while (used.has(name)) {
    i += 1
    name = `${prefix}${i}`
  }
  used.add(name)
  return name
}

const RAIL_DEFS = new Set(['power_source', 'ground', 'junction'])

/** The signal (non-power) input + output pins of a gate, by the shared classification heuristics. */
function gatePins(gate: BlockData): { out: BlockPort | undefined; ins: BlockPort[] } {
  const pins = gate.ports.filter((p: BlockPort) => !POWER_PORT_IDS.has(p.id.toLowerCase()))
  return { out: pins.find(isOutputPort), ins: pins.filter((p) => !isOutputPort(p)) }
}

/** A design that IS a single primitive gate → a one-instance module (its own pins are the ports). */
function exportGateModule(gate: BlockData, moduleName: string, used: Set<string>): string {
  const { out, ins } = gatePins(gate)
  const keyword = PRIMITIVE_OF[gate.name]
  const inNames = ins.map((p) => sanitizeIdent(p.id, used))
  const outName = out !== undefined ? sanitizeIdent(out.id, used) : freshName('y', used)
  const lines = [
    '// Generated by ChipBlocks — structural Verilog (IEEE 1364-2005).',
    `module ${moduleName}(${[...inNames, outName].join(', ')});`,
    inNames.length > 0 ? `  input ${inNames.join(', ')};` : '',
    `  output ${outName};`,
    '',
    keyword !== undefined ? `  ${keyword} g0(${[outName, ...inNames].join(', ')});` : '',
    'endmodule',
  ].filter((l) => l !== '')
  return `${lines.join('\n')}\n`
}

/**
 * Export a gate block as a structural Verilog module. Returns the Verilog text + any warnings (parts that
 * are not Verilog gate primitives are REPORTED, never faked — the same honesty as the SPICE/KiCad I/O).
 */
export function exportVerilog(block: BlockData): { verilog: string; warnings: string[] } {
  const warnings: string[] = []
  const used = new Set<string>([...RESERVED])
  const moduleName = sanitizeIdent(block.name || 'design', used)

  // A design that is itself a single primitive gate has no internal wiring to walk — emit it directly.
  if (isLogicGate(block)) {
    return { verilog: exportGateModule(block, moduleName, used), warnings }
  }

  // Flatten the design to its GATE CELLS (stop at gates — don't expand to transistors), then resolve nets.
  const top: CanvasNodeLike = {
    id: 'top',
    position: { x: 0, y: 0 },
    data: { definition: 'block', block },
  }
  const flat = flattenBlocks([top], [], isLogicGate)
  const { rootOf } = buildNets(flat.edges as CanvasEdgeLike[])

  // A net's identity: its union-find root when the endpoint is wired, else the endpoint itself. An
  // edge-less pin — e.g. a module output that no OTHER gate reads internally, or a single-fanout input —
  // is still a real net; keying by the endpoint lets the module port and its single gate pin, which
  // SHARE that exact endpoint, resolve to the SAME wire name (rootOf alone would leave both dangling).
  const nameByKey = new Map<string, string>()
  const netKey = (nodeId: string, handle: string): string =>
    rootOf(endpointKey(nodeId, handle)) ?? endpointKey(nodeId, handle)
  const netName = (nodeId: string, handle: string): string => {
    const key = netKey(nodeId, handle)
    const existing = nameByKey.get(key)
    if (existing !== undefined) return existing
    const name = freshName('w', used)
    nameByKey.set(key, name)
    return name
  }

  // Module interface = the design's SIGNAL ports (power ports are dropped — Verilog gate logic has no
  // supply pins). Direction by the same heuristics the logic engine uses. Reserve each port's net first.
  const signalPorts = block.ports.filter((p) => !POWER_PORT_IDS.has(p.id.toLowerCase()))
  const inputs: string[] = []
  const outputs: string[] = []
  const portOrder: string[] = []
  for (const p of signalPorts) {
    const inner = flat.portTarget.get(`top/${p.id}`)
    if (inner === undefined) {
      warnings.push(`port "${p.id}" is not connected inside the design; omitted`)
      continue
    }
    const pname = sanitizeIdent(p.id, used)
    // reserve the port name for its net — by endpoint key, so it binds even when the pin is edge-less
    nameByKey.set(netKey(inner.nodeId, inner.handleId), pname)
    portOrder.push(pname)
    if (isOutputPort(p)) outputs.push(pname)
    else inputs.push(pname)
  }

  // Gate instantiations — one primitive per gate cell, output-first, powerless.
  const instances: string[] = []
  let gateIdx = 0
  for (const node of flat.nodes) {
    const gate = node.data.block
    if (gate === undefined || !isLogicGate(gate)) {
      const def = node.data.definition
      if (def !== undefined && !RAIL_DEFS.has(def)) {
        warnings.push(`part "${def}" skipped — not a Verilog gate primitive`)
      }
      continue
    }
    const keyword = PRIMITIVE_OF[gate.name]
    if (keyword === undefined) {
      warnings.push(`gate "${gate.name}" has no Verilog primitive; skipped`)
      continue
    }
    const { out: outPin, ins: inPins } = gatePins(gate)
    if (outPin === undefined) {
      warnings.push(`gate "${gate.name}" has no output pin; skipped`)
      continue
    }
    const outNet = netName(node.id, outPin.id)
    const inNets = inPins.map((pp) => netName(node.id, pp.id))
    instances.push(`  ${keyword} g${gateIdx}(${[outNet, ...inNets].join(', ')});`)
    gateIdx += 1
  }

  // Internal wires = every named net that is not a module port.
  const portNames = new Set([...inputs, ...outputs])
  const wires = [...new Set(nameByKey.values())].filter((n) => !portNames.has(n))

  const lines: string[] = [
    '// Generated by ChipBlocks — structural Verilog (IEEE 1364-2005).',
    '// A representation of the real gate design; the gates remain the source of truth.',
    `module ${moduleName}(${portOrder.join(', ')});`,
  ]
  if (inputs.length > 0) lines.push(`  input ${inputs.join(', ')};`)
  if (outputs.length > 0) lines.push(`  output ${outputs.join(', ')};`)
  if (wires.length > 0) lines.push(`  wire ${wires.join(', ')};`)
  lines.push('')
  lines.push(...instances)
  lines.push('endmodule')

  return { verilog: `${lines.join('\n')}\n`, warnings }
}
